### ISSUE TITLE
"Favorite Media Cannot Be Constructed" Error Message 

### ISSUE THREAD

**Issue by Cherrilovesjoot** [Dastan21/BDAddons#100]
I've tried restarting my pc, uninstalling/fixing better discord but nothing seems to be working :( please fix this issue thanks!

**Comment by maenDisease** [comment]
Duplicate of https://github.com/Dastan21/BDAddons/issues/94 and addressed in commit https://github.com/Dastan21/BDAddons/commit/053c21f07fea721b220a9973382e0b79f5f7f419.
Please redownload the plugin from the lastest commit https://raw.githubusercontent.com/Dastan21/BDAddons/053c21f07fea721b220a9973382e0b79f5f7f419/plugins/FavoriteMedia/FavoriteMedia.plugin.js
