### ISSUE TITLE
Favorite Media: Images do not load and are all stacked on each other.

### ISSUE THREAD

**Issue by SaenaiNL** [Dastan21/BDAddons#103]
This started happening a few days ago, the menu loads only the most recent images, and all images are stacked upon each other.
[Image here](https://i.imgur.com/vhglfpB.png).

**Comment by Masono03** [comment]
second this am on newest canary build

**Comment by Epicgamer92** [comment]
Third to this, playing on the most recent build

**Comment by TxRichardxT** [comment]
This didnt happen to me until this day so i have the same problem

**Comment by bob-carter** [comment]
Same

**Comment by Dastan21** [comment]
Fixed in v1.5.21

**Comment by themasterswordmaster** [comment]
still happening for me after i updated

**Comment by Dastan21** [comment]
Happens for the images favorited before the update.

**Comment by TxRichardxT** [comment]
> still happening for me after i updated

Same, i tried removing the config.json with a old back up and worked but my new saves still bugged and i cant see them, also i think when i tried to move one image to a category it duplicates into the category and stays in the same place

**Comment by bob-carter** [comment]
> Fixed in v1.5.21 The bug occured when favoriting images. So you must reset the images you favorited from past few days and favorite them again, so that it saves the correct width/height of the images.

Didn't work, in fact any fav I removed and readded won't show up after being added back.

**Comment by Dastan21** [comment]
As a temporary fix you can favorite with the context menu.

**Comment by bob-carter** [comment]
> As a temporary fix you can favorite with the context menu.

Still does the same thing, only shows the last 2 fav'ed and nothing else.

**Comment by Dastan21** [comment]
Check the in the `FavoriteMedia.config.json` file, the latest elements in the `image/medias` section, if they have width/height properties and they are different that "100%".

**Comment by bob-carter** [comment]
> Check the in the `FavoriteMedia.config.json` file, the latest elements in the `image/medias` section, if they have width/height properties and they are different that "100%".

Thanks, deleting the config seemed to work. Should have fought to do that first.

**Comment by TxRichardxT** [comment]
> 



> > Check the in the `FavoriteMedia.config.json` file, the latest elements in the `image/medias` section, if they have width/height properties and they are different that "100%".
> 
> Thanks, deleting the config seemed to work. Should have fought to do that first.

What did you do to fix it? you removed the whole file? or just deleted those that had 100%?

**Comment by themasterswordmaster** [comment]
> > 
> 
> > > Check the in the `FavoriteMedia.config.json` file, the latest elements in the `image/medias` section, if they have width/height properties and they are different that "100%".
> > 
> > 
> > Thanks, deleting the config seemed to work. Should have fought to do that first.
> 
> What did you do to fix it? you removed the whole file? or just deleted those that had 100%?

I fixed mine by opening the config and searching for any files with 100% width, and copy-pasting the width and height from another file that worked
