### ISSUE TITLE
FavoriteMedia: Could not be constructed

### ISSUE THREAD

**Issue by LucasIsRed** [Dastan21/BDAddons#105]
<html>
<body>

FavoriteMedia: Could not be constructed.
--
2 | at Object.initializeAddon (<anonymous>:4:306871)
3 | at Object.loadAddon (<anonymous>:4:268358)
4 | at Object.loadAddon (<anonymous>:4:305909)
5 | at Object.loadAllAddons (<anonymous>:4:270636)
6 | at Object.initialize (<anonymous>:4:265083)
7 | at Object.initialize (<anonymous>:4:305119)
8 | at Object.startup (<anonymous>:4:367198)

</body>
</html>

**Comment by maenDisease** [comment]
Duplicate of #95
