### ISSUE TITLE
Images are blank and overlapped

### ISSUE THREAD

**Issue by jizzyjdog** [Dastan21/BDAddons#109]
This issue has been going on for a few days. Even after the bug fix recently to fix the overlapping, mine are still the exact same, they show as grey and overlapped. When I click a random overlapping grey box, a random favorited image pops up. [see here](https://imgur.com/a/vyS7far)

**Comment by Dastan21** [comment]
Unfavorite all THEN favorite them back.

**Comment by jizzyjdog** [comment]
worked, thanks. amazing plugin btw :D

**Comment by Kiq33** [comment]
Unfavoriting then favoriting again works but I had to do it dozens of times by sending every pic in a chat.

**Comment by NerdKnight66** [comment]
This really needs to be fixed

**Comment by Dastan21** [comment]
> This really needs to be fixed

This is fixed already for the next images, but you have to fix by yourself the one that are bugged.
See https://github.com/Dastan21/BDAddons/issues/103#issuecomment-1191763893

**Comment by NerdKnight66** [comment]
Oh ok.

**Comment by DuckersMcQuack** [comment]
> > This really needs to be fixed
> 
> This is fixed already for the next images, but you have to fix by yourself the one that are bugged. See the 2nd comment and [#103 (comment)](https://github.com/Dastan21/BDAddons/issues/103#issuecomment-1191763893)

What if the images i wanna back up and re favorite doesn't show up? As there's lots of empty space where i can scroll a little, then some images are suddenly only loading on the far right side and left side is just nothing.

![image](https://user-images.githubusercontent.com/9039370/181416033-ce38d6c3-3a3e-476c-b849-63b11053bbd1.png)

**Comment by ronfino** [comment]
![image](https://user-images.githubusercontent.com/77462428/181722707-a84c2538-47bd-472f-95fd-bb95e6eb0fa9.png)
same issue here

**Comment by Dastan21** [comment]
![image](https://user-images.githubusercontent.com/58090137/181722999-9a31657d-7098-44d9-b5ec-09eeff1a1014.png)

**Comment by ronfino** [comment]
Fixed, thanks!

**Comment by DuckersMcQuack** [comment]
> ![image](https://user-images.githubusercontent.com/77462428/181722707-a84c2538-47bd-472f-95fd-bb95e6eb0fa9.png) same issue here

Actually found a workaround.  Open the favoritemedia.config in notepad, copy paste each cdn.discordapp.com link or just select all and copy, if you have a personal server, make a new throwaway channel and paste the entire code, and each link should embed so you can then unfavorite all and favorite again.

![image](https://user-images.githubusercontent.com/9039370/181771472-0cb996bd-90ba-4f29-9829-6fa529a1f07f.png)

**Comment by SmokePuddingEveryday** [comment]
Sorry to post on this again, but experiencing this again as of yesterday. First time this happened a few weeks ago I went and unfavorited every single image and everything worked perfectly up until yesterday where the same overlapping issue is occurring.

BD Version: 1.6.3
Plugin version: 1.5.26

**Comment by Dastan21** [comment]
Update the plugin to the latest version and reset only medias that don't have width/height properties set (number, not "100%" or null) in `FavoriteMedia.config.json`.
