### ISSUE TITLE
Can't have more GIFs

### ISSUE THREAD

**Issue by OwlCacone** [Dastan21/BDAddons#110]
After a recent update (I want to say around 2 or so weeks ago) Favorite Media had stopped working and after it was working again, all my GIFs, that I had before installing the plugin, were in my favorites folder and I couldn't add any more as I had reached the regular discord limit for them. All other media is fine, only GIFs got affected

**Comment by Dastan21** [comment]
GIFs aren't afffected by the plugin, it's Discord's limit.

**Comment by OwlCacone** [comment]
That's weird, because I swear that before that big update happened, I had hundreds more saved thanks to the plugin
