### ISSUE TITLE
[FavoriteMedia] 'Well This Is Awkward' on startup Canary

### ISSUE THREAD

**Issue by maenDisease** [Dastan21/BDAddons#111]
![image](https://user-images.githubusercontent.com/90428263/182514081-cf07eccb-52b0-48ac-a67d-c92f23f23b32.png)
```
Canary 139676 (6b089cc)
BetterDiscord 1.5.3-Hotfix2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)
```

**Comment by ohitstom** [comment]
Same here, non canary.

**Comment by Dastan21** [comment]
Update ZerePluginLibrary.

**Comment by ohitstom** [comment]
just did, no change.
![image](https://user-images.githubusercontent.com/22730962/182795152-d8cddb1f-d190-40eb-a465-22ae8af0f33e.png)
![image](https://user-images.githubusercontent.com/22730962/182795201-500ce517-8671-4eb4-a46d-effd6a906016.png)
![image](https://user-images.githubusercontent.com/22730962/182795206-55778b03-192d-42f3-9c7b-b02d635b13fd.png)

**Comment by ohitstom** [comment]
It updated to the wrong version initially, had to reinstall both favoritemedia and zerespluginlibrary manually!
Seems alright now.

**Comment by maenDisease** [comment]
Fixe with ZeresPluginLibrary update
