### ISSUE TITLE
FavoriteMedia cant be constructed.

### ISSUE THREAD

**Issue by Masono03** [Dastan21/BDAddons#112]
Started today. As title states.

Canary 141316 (e700422)
BetterDiscord 1.6.2
Host 1.0.48 Windows 10 64-Bit (10.0.19044)

**Comment by Ama1999** [comment]
Yeah can confirm, build is broken on the latest Discord version (with latest BD).

**Comment by Dastan21** [comment]
Fixed in 1.5.23
