### ISSUE TITLE
Favorite Media: @name error

### ISSUE THREAD

**Issue by derkrr** [Dastan21/BDAddons#113]
When I load onto Discord it gives me this error

![image](https://user-images.githubusercontent.com/88912712/184453437-66b10f99-eb72-4096-8c9a-32ccd03aab33.png)

**Comment by Dastan21** [comment]
Download manually the update here https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js (right-click and save as file).
