### ISSUE TITLE
favourite media images overlapping each other, glitchy, wont show/load most of the images

### ISSUE THREAD

**Issue by sultanxsalah** [Dastan21/BDAddons#115]
i open images tab and it glitches out and i cant see most of the images and the video tab works just images not working you already posted a fix for this but its still an issue for me i tried repairing betterdiscord and reinstalling your mod still hasnt fixed the issue
![image](https://user-images.githubusercontent.com/24615231/184609215-6629c6f9-3cf0-424b-aeac-4fcf6721a344.png)

**Comment by Dastan21** [comment]
Duplicate https://github.com/Dastan21/BDAddons/issues/109#issuecomment-1199037630.
