### ISSUE TITLE
Wrong RU localization

### ISSUE THREAD

**Issue by Dawaren** [Dastan21/BDAddons#118]
"Картина" -"Изображения"
"видео" - "Видео"

**Comment by Dastan21** [comment]
Is the B in "Видео" caps everytime or only at the beginning of a sentence ? like "Аудио" (ex: "Не удалось скачать аудио")

**Comment by Dawaren** [comment]
Yes, it's correct, sorry for long answer
![image](https://user-images.githubusercontent.com/84898190/185725461-8e1ee85d-7fdb-4f45-ab43-5bc48e1d6958.png)
Here "Картина" change on "Изображения"
