### ISSUE TITLE
New update causing Google Translate plugin to not show button

### ISSUE THREAD

**Issue by OsoaGitHub** [Dastan21/BDAddons#12]

**Comment by Dastan21** [comment]
Can you link me the plugin so that I can test pls ?

**Comment by OsoaGitHub** [comment]
Wait that's strange it's working now. I'll keep this open because it seems to be iffy, if it keeps working I'll close but it's fine right now.
Plugin can be found at bottom of [this](https://mwittrien.github.io/) page.

**Comment by Dastan21** [comment]
It seems to be working fine after a restart.

**Comment by OsoaGitHub** [comment]
Yeah, that’s what happened to me too. I will close now
