### ISSUE TITLE
plugin hasnt been working for like 2 months. dont know what this means but heres the error it gives me

### ISSUE THREAD

**Issue by DaveShotYa** [Dastan21/BDAddons#121]
![favorite media error](https://user-images.githubusercontent.com/105587006/185778435-f04ad742-432a-4c13-a56b-b83d8746bd92.jpg)

**Comment by Dastan21** [comment]
Download manually the latest version here (right-click, save as): https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js
