### ISSUE TITLE
Images tab broken

### ISSUE THREAD

**Issue by JustaFloatingEyeYT** [Dastan21/BDAddons#122]
I really hope this isn't a duplicate, but my images tab is broken and is still after reinstalling. All I see are 2 big squares.
![image](https://user-images.githubusercontent.com/79027427/186026217-4853e07b-8b8b-4aa1-99ad-a1c034166db3.png)

**Comment by Dastan21** [comment]
Doesn't happen for me yet... So it is TBD, end.

**Comment by JustaFloatingEyeYT** [comment]
> And it might be related to an old issue [#109 (comment)](https://github.com/Dastan21/BDAddons/issues/109#issuecomment-1219146067)

That's the fix, which would mean this issue is a duplicate of that one.
