### ISSUE TITLE
[FavoriteMedia] The Category spot is kinda weird

### ISSUE THREAD

**Issue by jasonzgames** [Dastan21/BDAddons#123]
### Discord Build

Stable

### Discord Version

Stable 143592 (0fccba9)

### Plugin Version

1.5.27

### Steps To Reproduce

I dont know why its like that

### Describe the bug

Idk how to describe it just look

### Screenshots

![fix plz](https://user-images.githubusercontent.com/63572031/186831240-62b75adb-333b-4f58-b08c-cfa85314afd4.PNG)
![fix plz2](https://user-images.githubusercontent.com/63572031/186831593-27fdf11a-217b-489c-b524-5e2f34d27d14.png)

**Comment by 0x03c** [comment]
> ### Discord Build
> 
> Stable
> ### Discord Version
> 
> Stable 143592 (0fccba9)
> ### Plugin Version
> 
> 1.5.27
> ### Steps To Reproduce
> 
> I dont know why its like that
> ### Describe the bug
> 
> Idk how to describe it just look
> ### Screenshots
> 
> ![fix plz](https://user-images.githubusercontent.com/63572031/186831240-62b75adb-333b-4f58-b08c-cfa85314afd4.PNG) ![fix plz2](https://user-images.githubusercontent.com/63572031/186831593-27fdf11a-217b-489c-b524-5e2f34d27d14.png)

Can be linked to .gif
Try to remove the .gif from your images/videos

**Comment by Dastan21** [comment]
@jasonzgames 
Check this too https://github.com/Dastan21/BDAddons/issues/109#issuecomment-1219146067

**Comment by jasonzgames** [comment]
Thank you so much!!!
