### ISSUE TITLE
[HideEmbedLink]: Plugin not working

### ISSUE THREAD

**Issue by Nirgranth** [Dastan21/BDAddons#124]
### Discord Build

Stable

### Discord Version

Stable 144494 (22d9861)

### Plugin Version

2.0.0

### Steps To Reproduce

Stable 144494 (22d9861)
BetterDiscord 1.6.3
Host 1.0.9006
Windows 11 64-Bit (10.0.22000)

### Describe the bug

Plugin not working

### Screenshots

![image](https://user-images.githubusercontent.com/48947296/187493963-29d45cce-0acc-49c5-acf2-dbab70a40873.png)

![image](https://user-images.githubusercontent.com/48947296/187494319-34367380-c76b-47ed-9a49-48b4f0890902.png)

**Comment by Dastan21** [comment]
![Discord_b2uCfqAypY](https://user-images.githubusercontent.com/58090137/187497144-ed5454c9-e832-4489-b6f0-a0f8743083e2.gif)

Weird...
Does the message contains other contents ?

**Comment by Nirgranth** [comment]
No?
![image](https://user-images.githubusercontent.com/48947296/187724555-e0ad194f-cdd3-438e-b8b2-76c2ef06eff2.png)

**Comment by Dastan21** [comment]
Try disabling others plugins to check if it is in conflict with one of them.

**Comment by Nirgranth** [comment]
![image](https://user-images.githubusercontent.com/48947296/187745655-e74721f6-0ce6-4008-9167-ea4512be44a8.png)
![image](https://user-images.githubusercontent.com/48947296/187745789-f07a38f1-8f37-4210-a6ec-0caaec04c649.png)
![image](https://user-images.githubusercontent.com/48947296/187745947-c0b356a2-9021-4ad8-9c76-2bbb5c3a5de2.png)

**Comment by Tharki-God** [comment]
changing` ret.props.children[0]` to` ret.props.content `works but the show link button aint showing up

**Comment by Nirgranth** [comment]
> ![image](https://user-images.githubusercontent.com/48947296/187745655-e74721f6-0ce6-4008-9167-ea4512be44a8.png) ![image](https://user-images.githubusercontent.com/48947296/187745789-f07a38f1-8f37-4210-a6ec-0caaec04c649.png) ![image](https://user-images.githubusercontent.com/48947296/187745947-c0b356a2-9021-4ad8-9c76-2bbb5c3a5de2.png)

only one on bot doesn't work

**Comment by Nirgranth** [comment]
@Dastan21 any updates?

**Comment by Dastan21** [comment]
Disable the current HideEmbedLink and add [this one](https://github.com/Dastan21/BDAddons/files/9635766/HideEmbedLinkDebug.plugin.js.zip), then:
1. Open the DevTool
2. Clear the console
3. Hover an embed message
4. Right-click in the console: 'Save as...'
5. Send the log file

**Comment by Nirgranth** [comment]
Works now
