### ISSUE TITLE
[FavoriteMedia]: Crashes my discord sometimes

### ISSUE THREAD

**Issue by RDP8** [Dastan21/BDAddons#125]
### Discord Build

Stable

### Discord Version

Stable

### Plugin Version

1.6.0

### Steps To Reproduce

Just click on a server and it crashes and my crash detector plugin says it suspects favorite media of being the cause of the crash, then I disable the plugin and then I have no issues. 

### Describe the bug

It crashes my discord when I click on any server.

**Comment by Dastan21** [comment]
For me is was APlatformIndicators.plugin, I'll check in the next few days.

**Comment by RDP8** [comment]
Seems to not be crashing my discord anymore, I have no idea with its working now lmao.
