### ISSUE TITLE
[FavoriteMedia]: Image Panel stacking and Layering bug

### ISSUE THREAD

**Issue by FO1R** [Dastan21/BDAddons#126]
### Discord Build

Stable

### Discord Version

Stable 146284 (57b3d6d)

### Plugin Version

1.6.3

### Steps To Reproduce

1. Have Images Favored
2. Open Favored Images tab
3. Scroll down to observe

### Describe the bug

The Bug seems to be a layering or stacking issue only on Images.
At the top of the panel some Images are randomly stacked with no preview (all grey).
A bit lower down there is the "Nothing to see here" Image layered over the whole panel, over top where some of the images start to become visible. A bit lower everything will appear normal except all of the images favored before the update that broke the panel appear to be gone but in fact they are all stacked randomly at the top all grey. Even lower down the structure of the showed images seems to break into a single line.

### Screenshots

![image](https://user-images.githubusercontent.com/44537384/189536423-91f635cf-a632-47a0-b42a-53306a77f76b.png)
![image](https://user-images.githubusercontent.com/44537384/189536435-d99ec5fc-807c-4173-b2c8-1489cf74c204.png)
![image](https://user-images.githubusercontent.com/44537384/189536553-45c3d771-a663-4c3f-b1bd-7c252a4fa7b8.png)
![image](https://user-images.githubusercontent.com/44537384/189536573-55284325-fc98-499b-86bb-0884e94db386.png)
![image](https://user-images.githubusercontent.com/44537384/189536681-5d15b8e4-a84e-4157-84ab-cb4a8f8b7d84.png)
![image](https://user-images.githubusercontent.com/44537384/189536588-32d8440f-ddd0-4424-b0d6-e55742fcedec.png)
![image](https://user-images.githubusercontent.com/44537384/189536639-d5ea41e5-e4c4-43f3-bc19-a8d973b15c6c.png)

**Comment by Dastan21** [comment]
https://github.com/Dastan21/BDAddons/issues/109#issuecomment-1219146067
