### ISSUE TITLE
[FavoriteMedia]: Local cache of images

### ISSUE THREAD

**Issue by DuckersMcQuack** [Dastan21/BDAddons#128]
### Describe the solution you'd like

I want a feature request to have a offline cache with the addon to much quicker load the saved images than having to buffer them from the web every time i want to fetch an image.

**Comment by Dastan21** [comment]
Should load faster in 1.7.0, I have added medias preloading (before even opening media tabs).

**Comment by ToppyTopology** [comment]
Is caching not possible? Its not really that great that it redownloads media everytime you restart the app

**Comment by noblereign** [comment]
please implement actual caching dawg it is not fun opening discord just to realize that you have accidentally spammed discord's CDN with like 4 thousand requests to load gifs, i literally cant use this plugin rn 😭

**Comment by DeCat4** [comment]
If you're going to add image caching perhaps add an option to compress the previews, this is what discord does and it's effective.

I've noticed the plugin shits itself to 4K images.

Also any chance that with the caching feature you can make it so all favorited content is downloaded locally on a chosen directory to avoid dead media?

**Comment by DuckersMcQuack** [comment]
Scrolling too fast, as in one line, wait for all images to buffer, load next line, scrolling faster than this crashes the client. So a local cache would definitely be welcome :P

**Comment by bob-carter** [comment]
Just here to mention that if this feature was added, it'd fix the issue of media pre-views breaking with Discords New changes.

**Comment by Dastan21** [comment]
Medias previews (image, video, gif) are now getting cached in v1.10.0.
