### ISSUE TITLE
[FavoriteMedia]: Option to disable star on top of medias

### ISSUE THREAD

**Issue by jons-repo** [Dastan21/BDAddons#129]
### Describe the solution you'd like

Options to remove star in medias since we already have a right click menu option to add media to favorites. Stars in favorites menu is fine though it doesnt matter there.

### Screenshots

![image](https://user-images.githubusercontent.com/54567183/192051324-78447b03-79a8-45a6-80f2-7196a6ae2561.png)

**Comment by Dastan21** [comment]
All medias or just videos ?

**Comment by jons-repo** [comment]
> All types of medias or just videos ?

I'd say you have options where you can choose which.

**Comment by Dastan21** [comment]
Addeed in v1.6.1 👍
