### ISSUE TITLE
FavoriteMedia: Gif/Sticker tab not closing after sending gif/sticker

### ISSUE THREAD

**Issue by miles352** [Dastan21/BDAddons#13]
I think this is a result of adding shift to not close somehow, but I doubt this is intended. I personally like it but just wanted to let you know.

**Comment by Dastan21** [comment]
Can't reproduce, can you please give the steps ?

**Comment by miles352** [comment]
Not sure how it happened, might have something to do with the plugin getting an update. I couldn't reproduce again, but I'll let you know if it happens again.
