### ISSUE TITLE
[FavoriteMedia]: Option to aways upload as file

### ISSUE THREAD

**Issue by CandyIsAbsolute** [Dastan21/BDAddons#130]
### Describe the solution you'd like

Would be really cool if there's an option to toggle whether media would get sent as a link or a file.

### Screenshots

![image](https://user-images.githubusercontent.com/98654154/192135755-fd7d0279-5a6f-49fc-8e8e-a39976b5f457.png)

**Comment by Dastan21** [comment]
Added in v1.6.2 👍
