### ISSUE TITLE
[FavoriteMedia]: Not working since the last Discord update

### ISSUE THREAD

**Issue by BrandyKoopa** [Dastan21/BDAddons#131]
### Discord Build

Stable

### Discord Version

Stable 149549 (1e1ae6d)

### Plugin Version

Version: 1.6.0

### Steps To Reproduce

1 download the plugin
2 install the plug in
3 gets an error

### Describe the bug

gets an error installing the plugin

### Screenshots

![Screenshot_2](https://user-images.githubusercontent.com/26722628/192810984-dcd321d5-b299-44fc-8383-ca8beb02f2b0.png)

**Comment by Komrade-Yanouchka** [comment]
all plugins have stopped working since the last BD update.

**Comment by Silvia-Dragoness** [comment]
More accurately, Discord pushed an update which completely broke BD in its entirety.  The BD folks have got its core functionality back up and running, but nearly every plugin will need to be updated (if not entirely rewritten) before they'll work again.  See the official BD server for more info (they've also got a thread for tracking plugin updates in response to this).

**Comment by jizzyjdog** [comment]
damn, do we know if the creator of this plugin has plans on fixing it? my literal most used and favorite plugin EVER. discord is hell without it, it was so useful and convenient.

**Comment by Dastan21** [comment]
I will when BD will be stable.
You know I use my own plugins too therefor I'm also very sad without them 😢

**Comment by HedTB** [comment]
it truly has, it's such a useful plugin (boy do i have many memes saved there)

**Comment by Cqiny** [comment]
wait will all the stuff i have saved be there when the plugin gets updated?

**Comment by Dastan21** [comment]
Hopefully yes, but you can create a backup by copying the file `FavoriteMedia.config.json` from your plugins folder.

**Comment by zluckytraveler** [comment]
@Dastan21 BD has just pushed a new update!

**Comment by Dastan21** [comment]
I know when they do don't worry x)

**Comment by StardustBytez** [comment]
what does 1.6.2 do? i got the update but it's still not working for me

**Comment by Dastan21** [comment]
It was an update from before the Discord breaking update, which was only accepted a few days ago.

**Comment by StardustBytez** [comment]
OOHH alright !! good to know :]

**Comment by ronfino** [comment]
:(

**Comment by Maximusl30** [comment]
Updates on Favorite Media?

**Comment by Maximusl30** [comment]
Is it a major issue with the code? Or are you able to just repub

**Comment by zluckytraveler** [comment]
> Is it a major issue with the code? Or are you able to just repub

It'll likely require a rewrite, just like every other plugin.

**Comment by Maximusl30** [comment]
Ah okay, I just want my meme's

**Comment by midnitefox** [comment]
> 

If you download jDownloader and paste the contents of your `FavoriteMedia.config.json` into its "Add New Links" function, it will automatically index all of your favorited media into individual downloads. Which you can then download all at once into a "Memes" folder or whatever you'd like to call it.

Worked well for me as a solution until the plugin is rewritten.

**Comment by Maximusl30** [comment]
Ah thank you! I'll be sure to do it.

**Comment by Kiq33** [comment]
Looking forward for the update. This plugin is genius.

**Comment by VirginitySnatcher** [comment]
Any news on when is the plugin going to be updated?

**Comment by Dastan21** [comment]
I don't really have the motivation on fixing it because of how many modules I have to replace.

**Comment by Ryuktheshinigamix** [comment]
shit so is this going to be abandoned?

**Comment by Dastan21** [comment]
Kind of, unless I get back to it or someone else fixes it.

**Comment by Ryuktheshinigamix** [comment]
I've legit been checking everyday since the 30th of sep...

**Comment by Ryuktheshinigamix** [comment]
Would money solve this issue? I can throw a hundo if need be.

**Comment by Komrade-Yanouchka** [comment]
> I've legit been checking everyday since the 30th of sep...

same

**Comment by Komrade-Yanouchka** [comment]
i'm sure some ppl would be happy to at lest help on the discord

**Comment by zeroquinc** [comment]
> I've legit been checking everyday since the 30th of sep...

same here

**Comment by envoriium** [comment]
i can't shitpost on discord anymore with favorite media
this is so sad

**Comment by Fluffacorn** [comment]
pain, all my homies know is pain

**Comment by zluckytraveler** [comment]
I'm sure if someone posts this plugin on the official BD discord someone will pick it up and fix it. It's happened many other times before with other plugins.

**Comment by envoriium** [comment]
who's gonna do it though

**Comment by ronfino** [comment]
Someone's gotta do it!

**Comment by Ryuktheshinigamix** [comment]
Bro Im begging, i'll pay. Pls. Its such a handy thing to have.

**Comment by Komrade-Yanouchka** [comment]
> Bro Im begging, i'll pay. Pls. Its such a handy thing to have.

yeah for me it's THE best plugin.

**Comment by ronfino** [comment]
It's a MUST have.

**Comment by Kiq33** [comment]
The must-have feature Discord is too evil to implement on the main software

**Comment by Komrade-Yanouchka** [comment]
yeah exactly. tbh if this plugin is not updated i don't have much use for better discord anymore.

**Comment by Ryuktheshinigamix** [comment]
> yeah exactly. tbh if this plugin is not updated i don't have much use for better discord anymore.

Honestly without FavoriteMedia, ShowAllMessageButtons and DiscordFreeEmojis I wouldnt have BD. 
Unfortunately only DiscordFreeEmojis Currently works.

**Comment by NorLOL** [comment]
I like penis

**Comment by Dastan21** [comment]
I'm locking comments on this issue as it is in standby. If I have any news, I will comment here tho.

**Comment by Dastan21** [comment]
Thanks to [Skamt](https://github.com/Skamt), a fix should be pushed within the day 😃
