### ISSUE TITLE
[FavoriteMedia]: Requesting Permission to Find someone to take over the Project?

### ISSUE THREAD

**Issue by Ryuktheshinigamix** [Dastan21/BDAddons#136]
### Describe the solution you'd like

As the title says I'd like Permission to ask around and find someone who will take over this Project as you've said before You don't really have the motivation on fixing it and It may as well become abandoned unless you get back to it or someone else fixes it. I want to look for that someone else since you delinced to fix it even when offered money and locked down the other thread. I really like this plugin its one of the main reasons i use BD so i'd really like to be able to use it again. Im happy to offer Money if you want to fix it and I also didnt really know a better way of contacting you so I appologise. What do you say?

**Comment by Aezaeo** [comment]
Ive been missing this plugin a lot as well. Same for me too, one of the main reasons I use betterdiscord.

**Comment by Dastan21** [comment]
Well, as my plugins are open source, anyone can fix it and open a Pull Request...

**Comment by Ryuktheshinigamix** [comment]
Okay Thank you for clarifying.

**Comment by Dastan21** [comment]
Thanks to [Skamt](https://github.com/Skamt), a fix should be pushed within the day 😃
