### ISSUE TITLE
[FavoriteMedia]: Can't click the star icon

### ISSUE THREAD

**Issue by zeroquinc** [Dastan21/BDAddons#139]
### Discord Build

Stable

### Discord Version

Latest

### Plugin Version

Latest

### Steps To Reproduce

1. I added the plugin to the plugin folder.
2. Enabled the plugin
3. You can't click the star.

### Describe the bug

You can't click the Star, nothing happens.

https://i.imgur.com/HBTZBWd.gif

**Comment by Dastan21** [comment]
Fixed 👍
