### ISSUE TITLE
[FavoriteMedia]: Can't insert any favorited pics

### ISSUE THREAD

**Issue by zeroquinc** [Dastan21/BDAddons#140]
### Discord Build

Stable

### Discord Version

Latest Stable

### Plugin Version

Latest

### Steps To Reproduce

1. Add fixed plugin to plugin folder
2. Favorite a picture
3. Try to insert the picture in the chat, nothing happens.

### Describe the bug

When you favorited a picture and click on it from the menu, it doesnt add it.

https://i.imgur.com/1De97Og.gif

**Comment by Dastan21** [comment]
😢

**Comment by Dastan21** [comment]
Any error in the console ?

**Comment by zeroquinc** [comment]
> Any error in the console ? Cuz it works fine on my end.

I'm about to give up tbh. I reinstalled Discord and BetterDiscord, reinstalled the plugin but still the same thing.

Also I can't open the console with CTRL+SHIFT+I, also with Devtools etc enable so not sure how I can help further...

**Comment by Dastan21** [comment]
Is the setting `developer.devTools` to true in the settings.json?

**Comment by zeroquinc** [comment]
```
{
"BACKGROUND_COLOR": "#202225",
"IS_MAXIMIZED": true,
"IS_MINIMIZED": false,
"DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING": true,
"developer.devTools": true
}
```

This is how my settings.json looks now. CTRL + SHIFT + I does absolutely nothing. So weird...

**Comment by Dastan21** [comment]
I meant this,
```js
{
  "developer": {
    "devTools": true
  }
} sorry
```

**Comment by zeroquinc** [comment]
Added that, still does nothing.

**Comment by zeroquinc** [comment]
Yeah, even after reloading.

**Comment by Dastan21** [comment]
Then you can open a support ticket on BD server.

**Comment by zeroquinc** [comment]
Why on BD server? Even with BetterDiscord uninstalled I have no way of opening the console.

**Comment by Dastan21** [comment]
ho my bad there are 2 settings.json, 1 for discord at `...\AppData\Roaming\discord` which contains the DANGEROUS_ENABLE_DEVTOOLS and 1 at `\AppData\Roaming\BetterDiscord\data\stable`. This is the latest that should contains the developer/devTools to true.

**Comment by Dastan21** [comment]
Try redownloading the [latest version](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js).

**Comment by zeroquinc** [comment]
> Try redownloading the [latest version](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js).

It worked!!!! But if I place back my old FavoriteMedia.config.json with old pictures in it back now I get the same issue.
I deleted the FavoriteMedia.config.json, restarted Discord so that the file get created and I get the same issue as before.

**Comment by Dastan21** [comment]
You mean the error when sending media ?

**Comment by zeroquinc** [comment]
> You mean the error when sending media ?

Yeah sorry I'll try to be more specific.

1. I installed your newest version, added a picture as favorite and I can insert it fine.
2. I placed the FavoriteMedia.config.json that I had backupped back in the plugins folder.
3. I restarted Discord and tried to click from the menu, I get the same console error as before.
4. I removed the FavoriteMedia.config.json file, restarted Discord so the file gets re-created.
5. I favorite a picture, try to send it but get the same console error as before.

**Comment by zeroquinc** [comment]
```
{
    "currentVersionInfo": {
        "version": "1.6.3",
        "hasShownChangelog": true
    },
    "image": {
        "medias": [
            {
                "url": "https://cdn.discordapp.com/attachments/742158497042399272/1042810172629856326/image.png",
                "width": 161,
                "height": 177,
                "name": "image"
            }
        ]
    }
}
```

**Comment by Dastan21** [comment]
Never mind it's my bad once again...

**Comment by zeroquinc** [comment]
Just did that, but still the console error when trying to send my only favorited pic.

**Comment by zeroquinc** [comment]
You are a legend mate.

My previous pics also work now!  The whole reason I use BD is because of this addon! Thank you so much man!
