### ISSUE TITLE
[FavoriteMedia]: New .plugin file doesn't work

### ISSUE THREAD

**Issue by ronfino** [Dastan21/BDAddons#141]
### Discord Build

Stable

### Discord Version

Stable 158183 (9ab8626)

### Plugin Version

1.6.2

### Steps To Reproduce

Start discord with latest .plugin file.

### Describe the bug

It simply won't activate the plugin.

### Screenshots

![image](https://user-images.githubusercontent.com/77462428/202511684-77ec38f1-fb05-45bf-893a-aa591010b1b0.png)
![image](https://user-images.githubusercontent.com/77462428/202512419-33a96e4f-6dd4-41fc-9dcd-c49d041a615c.png)

**Comment by Dastan21** [comment]
The plugin has not been validated yet on the BetterDiscord website. It should be in the next few days.
