### ISSUE TITLE
[FavoriteMedia]: Missing Preciously Favorited Images/Videos

### ISSUE THREAD

**Issue by JoeyDagger** [Dastan21/BDAddons#144]
### Discord Build

PTB

### Discord Version

160179 (fa86f65)

### Plugin Version

1.6.3

### Steps To Reproduce

N/A

### Describe the bug

All of my favorite images and videos that were previously saved before placing the plugin have disappeared.

**Comment by Dastan21** [comment]
Works fine for me on `Ptb 160507 (4b26cc0)`. Maybe try to get the [latest 1.6.3 version](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js) (there were many 1.6.3 versions)

**Comment by JoeyDagger** [comment]
That didn't seem to work either. And mind you, I'm referring to all of my favorited videos/images I had before the whole discord mod crash update.

**Comment by Dastan21** [comment]
1. Is there the empty message box?
2. Are the medias overlapped?
3. If you favorite new medias, do they appear in the tabs?
4. If you delete (backup first) `FavoriteMedia.plugin.js`, does it work again?

**Comment by JoeyDagger** [comment]
1.) All of the tabs show up, there is just nothing in them that I used to have before. 
2.) No, they show up fine and can be sent fine.
3.) Yes, but like I said, nothing previously saved before the update.
4.) Nope, still missing.

**Comment by Dastan21** [comment]
Well to me it looks like the config.json has been deleted. If you check in `FavoriteMedia.config.json`, are you previous medias links saved?

**Comment by JoeyDagger** [comment]
OH, it's saved in the config???? If that's the case I might be a very lucky man. I might have it somewhere, let me check.

**Comment by JoeyDagger** [comment]
When the crash happened, I saved all of the broken plugins in a folder and sure enough, I had it saved in there as well. You're a lifesaver man, thanks.
