### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#145]
### Discord Build

Stable

### Discord Version

Stable 160645 (9dbe547)

### Plugin Version

version 1.6.3

### Steps To Reproduce

Open up the plugin script editor through discord
change the btnsPosition Value from right to left
Nothing will happen

### Describe the bug

Judging from the note this feature is supposed to be put the shortcut icons for the favorite video,image,audio tabs to the left or right of the area where icons are placed, yet it doesn't.

also a tiny suggestion perhaps implement something to choose the exact positions of the icons? for example putting the favorite image icon to the right of the stickers icon. it's not necessary and probably useless but if possible it would be nice if being able to put the icons to the left of all the icons already in the textbox would be nice

### Screenshots

![image](https://user-images.githubusercontent.com/57727851/203978897-52bd3725-9d40-4276-b28d-1b403336dbd8.png)

**Comment by Dastan21** [comment]
As the dropdown settings are not working (from ZLibrary), you can edit it in the `FavoriteMedia.config.json` then restart, not directly from the plugin file.

And I added your suggestion in 1.6.4 👍
