### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by Aezaeo** [Dastan21/BDAddons#147]
### Discord Build

Stable

### Discord Version

BetterDiscord Core v1.8.2

### Plugin Version

FavoriteMedia v1.6.3

### Steps To Reproduce

1. right click a .gif image within discord.
2. you will see that the FavoriteMedia context menu modal is missing.

### Describe the bug

Not so much a bug, more of a feature that comes and goes with updates.

The issue is, not having the FavoriteMedia context Menu appear for .gif files. Currently, with .gif files the user is only able to "star" .gif files. There have been points in time when the user was able to add .gif files to a category of their choosing via FavoriteMedia context menu. 

I personally like favoriting .gifs to a "Gifs" category to separate my static images from .gif images. If you'd be so kind as to re-add this "feature" it would be very much appreciated.

**Comment by Dastan21** [comment]
This means that GIF were added to the 'Image' category, which shouldn't happen.
