### ISSUE TITLE
[FavoriteMedia]: Split view & vc chat doesn't work for favorite media UI

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#148]
### Discord Build

Stable

### Discord Version

Stable 161884 (ba55f09)

### Plugin Version

version 1.6.3

### Steps To Reproduce

Click favorite images button in VC Chat
Button brightens up but nothing opens

### Describe the bug

The favorite image button doesn't open the UI if you're using it from VC Chat, or to that extent split view because it doesn't appear if you're looking at a thread using split view.

**Comment by Dastan21** [comment]
Fixed in 1.7.0
