### ISSUE TITLE
[FavoriteMedia]: Crash with drop down menus

### ISSUE THREAD

**Issue by zany130** [Dastan21/BDAddons#149]
### Discord Build

Stable (From Arch Linux repos)

### Discord Version

Stable 162224 (e1ec9ed)

### Plugin Version

1.6.3

### Steps To Reproduce

1. open discord settings
2. go into voice & video
3. try to change the input or output device by clicking on the respective dropdown menu
4. see crash

### Describe the bug

drop down menus seem to crash with favorite media

**Comment by Dastan21** [comment]
Fixed some days ago, but I didn't increase the plugin version. Try with [this one](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js).

**Comment by zany130** [comment]
my bad should of tried looking in the closed issues https://github.com/Dastan21/BDAddons/issues/142
