### ISSUE TITLE
[FavoriteMedia]: META not found

### ISSUE THREAD

**Issue by zz4163** [Dastan21/BDAddons#151]
### Discord Build

Stable

### Discord Version

Stable 162224 (e1ec9ed)

### Plugin Version

1.6.4

### Steps To Reproduce

1. Download the addon to the BD Plugins folder.
2. Launch Discord.

### Describe the bug

It just shows META was not found every time I launch Discord, I tried to re-install the addon but it still doesn't work.

### Screenshots

![image](https://user-images.githubusercontent.com/57729823/205518770-2bdb8293-79b6-4c60-aafa-5a7005e719b0.png)

**Comment by Dastan21** [comment]
Copy-paste the content of [this](https://raw.githubusercontent.com/Dastan21/BDAddons/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js) into the .plugin.js file. I suppose you downloaded from the wrong button (which contains the html of the GitHub page, not the plugin code).

**Comment by zz4163** [comment]
Oh that fixed it. Thanks.
