### ISSUE TITLE
[FavoriteMedia]: New BD update broke Favorite Media

### ISSUE THREAD

**Issue by zz4163** [Dastan21/BDAddons#154]
### Discord Build

Stable

### Discord Version

Stable 163658 (28d41b4)

### Plugin Version

1.6.4

### Steps To Reproduce

1. download and update BD
2. done.

### Describe the bug

I'm pretty sure the new BD 1.8.3 update broke this plugin.

### Screenshots

![image](https://user-images.githubusercontent.com/57729823/207225180-776c019c-cabc-4abd-96a3-3418e83da4ec.png)

**Comment by TxRichardxT** [comment]
Yeah same here

**Comment by Dastan21** [comment]
Ad a temporary fix replace 'styleFixed' by 'colorDefault' line 321. I'm not pushing an update because the ContextMenu module makes Discord crash (right-clicking on a media or in the medias tabs) and a workaround hasn't be found yet.

**Comment by ronfino** [comment]
Ah shit, here we go again.

**Comment by maenDisease** [comment]
> Ad a temporary fix replace 'styleFixed' by 'colorDefault' line 321. I'm not pushing an update because the ContextMenu module makes Discord crash (right-clicking on a media or in the medias tabs) and a workaround hasn't be found yet.

For context, ContextMenu crashing has been addressed on the BD repo https://github.com/BetterDiscord/BetterDiscord/commit/5b8a173aa0a718f21b8403c84827de3df8d95818 (but hasn't been released as a release update).

**Comment by Xottabich0** [comment]
> styleFixed' by 'colorDefault' line 321

better discord just fixed that in new update 
![image](https://user-images.githubusercontent.com/84679590/207708130-61dc7630-400a-4233-8361-b1ca6719fe33.png)
