### ISSUE TITLE
[FavoriteMedia]: 1.6.4 Can't Compile with BD 1.8.4

### ISSUE THREAD

**Issue by maenDisease** [Dastan21/BDAddons#155]
### Discord Build

Stable

### Discord Version

Stable 164048 (25cf192)

### Plugin Version

1.6.4

### Steps To Reproduce

1. Install BD and Discord on fresh sandbox
2. Download FavoriteMedia from source

### Describe the bug

Unable to compile

### Screenshots

![image](https://user-images.githubusercontent.com/90428263/207713169-95fc3431-edd3-4d5a-b1ed-a4e943e7d291.png)
![image](https://user-images.githubusercontent.com/90428263/207713255-866dd134-8677-4068-b83e-f27787a09cfd.png)
![image](https://user-images.githubusercontent.com/90428263/207713985-04e1b860-a03d-4207-bbe8-506b6de0acf0.png)

**Comment by Dastan21** [comment]
Oops, forgot to push the last fix...

**Comment by maenDisease** [comment]
Fixed with the latest commit

**Comment by Dastan21** [comment]
Done. Still 1.6.4 (because it does no longer auto-update and it takes times to get verified on BD).

**Comment by Dastan21** [comment]
Too reactive 😮
