### ISSUE TITLE
[FavoriteMedia]: Error in code

### ISSUE THREAD

**Issue by Alexandr2005super** [Dastan21/BDAddons#159]
### Discord Build

Stable

### Discord Version

Stable 164497 (79ac697)

### Plugin Version

1.6.2

### Steps To Reproduce

1. Launch the Discord

### Describe the bug

I think I don't need to explain smth. You can all see in this screenshot.

### Screenshots

![image](https://user-images.githubusercontent.com/52630318/208120841-cae4019a-abc0-46bd-93c2-01c49f6b3278.png)

**Comment by Dastan21** [comment]
Duplicate https://github.com/Dastan21/BDAddons/issues/141
