### ISSUE TITLE
FavoriteMedia: gif tab content no longer fits

### ISSUE THREAD

**Issue by BuyMyMojo** [Dastan21/BDAddons#16]
With theme:
![image](https://user-images.githubusercontent.com/46948241/126542601-613fc5af-8fe3-4025-971d-de6c039f618d.png)

No theme:
![image](https://user-images.githubusercontent.com/46948241/126542654-4632be8c-77f8-4348-b337-80be63225646.png)

No plugin:
![image](https://user-images.githubusercontent.com/46948241/126542733-ad1e8ad8-97ea-4bfe-82c4-d7185eb5781f.png)

**Comment by Dastan21** [comment]
Just extend the tab :)

**Comment by BuyMyMojo** [comment]
You have blown my mind..
