### ISSUE TITLE
[HideEmbedLink]: Hide only media links option still hiding Twitter links

### ISSUE THREAD

**Issue by heartlessglasses** [Dastan21/BDAddons#160]
### Discord Build

Stable

### Discord Version

164806 (c2a78f3)

### Plugin Version

2.1.1

### Steps To Reproduce

1. Turn on the option to only hide links for media
2. See or share a Twitter link in its own message

### Describe the bug

With the option on, Twitter links should have their URLs shown above an embed, but they're still hidden.

**Comment by heartlessglasses** [comment]
Seems to be a problem with some other links as well, actually (example I just ran into: https://www.pdf24.org/en/), like it's not identifying what's an image/etc. and what isn't properly with some embeds.

**Comment by Dastan21** [comment]
Fixed in v2.1.2
