### ISSUE TITLE
[FavoriteMedia]: not sending selected media

### ISSUE THREAD

**Issue by Komrade-Yanouchka** [Dastan21/BDAddons#163]
### Discord Build

Stable

### Discord Version

Stable 166505 (fec0a45)

### Plugin Version

v1.6.5

### Steps To Reproduce

1. click the media i want to send
2. nothing happens

### Describe the bug

impossible to send media via left clicking the media. only work with right click followed by pressing the message button.

**Comment by Skamt** [comment]
Be more precis and say (**when uploading**) not when (**impossible to send media via left clicking**) If that's what you mean, although i don't see any other option there.

And yes the upload function seems busted, I'll see if i can figure out a fix for this when i have time unless someone else does so

**Comment by TxRichardxT** [comment]
Same thing here, i can't sent media doing just click on the video/Image

**Comment by Dastan21** [comment]
Fixed in 1.6.6
