### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by NightKnightNight** [Dastan21/BDAddons#164]
### Discord Build

Stable

### Discord Version

Stable 166894 (c43ed62)

### Plugin Version

1.6.5

### Steps To Reproduce

1. Right Click on selected media(Videos and Pictures)
2. Click upload (either with or without spoiler)
3. Nothing Uploads 

### Describe the bug

Over the past few days I have been trying to share some media through uploading the media throughout the favorite media addon and the media would never upload/send. If I left click it sends the media with an embed link but if I right click and upload it never uploads/sends.

**Comment by Dastan21** [comment]
Duplicate #163
