### ISSUE TITLE
[FavoriteMedia]: Add small customisation to the button layout, simplifying UI

### ISSUE THREAD

**Issue by J-GitHubAcc** [Dastan21/BDAddons#167]
### Describe the solution you'd like

Right now, there's 3 buttons that take up lots of room in the text box. Images, Videos, and Audio.

I think it's a good idea to change these to a singular button that opens the GIF/Sticker/Emoji/Images/Videos/Audio menu. It should open to whichever favorited media tab you had last selected. Maybe make the buttons icon a star?

This could be something that's not enabled by default but has a toggleable option in the config menu.

Thanks

**Comment by Dastan21** [comment]
There are options to disable any media button.
Ex: I personally rarely use the Audio tab
![image](https://user-images.githubusercontent.com/58090137/212757653-d9b007ab-ba8d-4c34-b860-619eb0e65462.png)
