### ISSUE TITLE
[FavoriteMedia]: Weird behavior with OpenAsar or MultiInstance

### ISSUE THREAD

**Issue by VoidsSpawn** [Dastan21/BDAddons#168]
### Discord Build

Stable

### Discord Version

Stable 170038 (edf3c54)

### Plugin Version

1.6.6

### Steps To Reproduce

Use OpenAsar or MultiInstance, favorite media on both accounts

### Describe the bug

Primary account's tab got replaced completely by the other account's empty favorites tab

**Comment by Dastan21** [comment]
As there is only 1 config file containing every media link, it's normal that bugs occur if both instance do differents things.
