### ISSUE TITLE
[FavoriteMedia]: Error when uploading media while replying to a message

### ISSUE THREAD

**Issue by TxRichardxT** [Dastan21/BDAddons#169]
### Discord Build

Stable

### Discord Version

170457 (9c7f6c8)

### Plugin Version

1.6.6

### Steps To Reproduce

1. You try to reply to someone using the reply button.
2.Open FavoriteMedia using video or image tab next to emoji button.
3. Searching what you want to send.
4. Left click in media i want to send.
5. Tab with all images/videos clooses and looks like the media was sent but it didn't send anything.
6. Same process and same results only thing changes its using right-click in media > upload > normal = won't sent media to the message i want to reply.

### Describe the bug

This only happens when i want to reply to a message with a media (Image, video) i try to do it both ways and in both the media won't be sended, what happens only clicking on it its that the media tab clooses and like bugs and you didn't reply with the media to the message and same happens but using the right-click option.

**Comment by Dastan21** [comment]
Is there any error in the console? It doesn't bug for me.

**Comment by TxRichardxT** [comment]
> Is there any error in the console? It doesn't bug for me. (I'm working on an upcoming version, maybe it is already fixed)

After doing the process again with console opened says "Replays must have a message reference"
And below that says 

(anonymous) 
  | r.<computed>
  | eval 
  | emit 
  | (anonymous) 
  | (anonymous) 
  | emit | 
  | endReadableNT |
  | processTicksAndRejections
  
  (Tell me if you need the blue text next to it but thats the error that appears)

**Comment by Dastan21** [comment]
This only happens when uploading a media. I've checked a bit and it may take some time to fix.

**Comment by Dastan21** [comment]
Fixed in 1.7.0
