### ISSUE TITLE
[FavoriteMedia]: Some gifs cannot be moved and must be catogerized manually via menu

### ISSUE THREAD

**Issue by Zzeyy** [Dastan21/BDAddons#170]
### Discord Build

Stable

### Discord Version

Stable 171621 (b20d67a)

### Plugin Version

1.7.0

### Steps To Reproduce

1. Open the GIF menu
2. View the Favorites tab
3. Try moving different gifs into any category
4. ERROR, some gifs cannot be moved with

### Describe the bug

Some gifs can't be moved with, some can be.

**Comment by Dastan21** [comment]
Fixed in the latest version
