### ISSUE TITLE
[FavoriteMedia]: Instant upload broken

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#173]
### Discord Build

Stable

### Discord Version

table 172394 (287c8cd)

### Plugin Version

1.7.0

### Steps To Reproduce

Try to upload a tenor gif with the instant upload for both
and try to upload any gif instantly (take a little too long, idk if it can be fixed)

### Describe the bug

Instant upload is mostly broken:

if you have the instant upload option enabled it'll refuse to upload tenor gifs
Uploading is too slow, takes like a whole second to post the image compared to before when it was instant

Same behaviour goes for the other option, if i click a tenor gif it won't link it to the message

**Comment by Dastan21** [comment]
1. Uploads should work again (1.7.1)
2. I have changed (from 1.6 to 1.7) how medias are uploaded because it couldn't work while replying to another message, it should only take like 1 or 2 more second at worse

**Comment by DeCat4** [comment]
V.1.7.2 Update sitll hasn't fixed them, it takes at best 5 seconds for most images.

I do have a lot of categories, probably around 100+ images in total saved but i have media previews disabled and instant upload or even non instant takes way too long to send it.

but if i right click and send upload it's instant, not that i know how java works but isn't it possible to use the same functions as the upload button for instant or non instant upload?

**Comment by Dastan21** [comment]
Could you provide a video/gif of the issue pls?

**Comment by DeCat4** [comment]
(Sorry for all the black boxes but privacy)
https://user-images.githubusercontent.com/57727851/222718902-0c7da9dc-7434-4f85-8303-0d7e606fed92.mov

The beginning Shows discord's gif picker, idk how big of a difference between images and gifs there is but it's instant and i think i have about 70+ gifs saved.

Now i was a bit wrong with my earlier comment, the issue seems to be that it needs me to select a second file because it doesn't send at all if i only select one file (If i select the same one twice it'll do it) but again this is still annoying to have to double click

**Comment by DeCat4** [comment]
Also seems to be an issue mainly with the send as file option, link works fine but this is still a major bug

**Comment by Dastan21** [comment]
What are your settings for "Always upload as file" and "Send/upload instantly medias"?

**Comment by Dastan21** [comment]
Do you use OpenAsar? If you don't know, probably not.

**Comment by Dastan21** [comment]
Is this still an issue?

**Comment by DeCat4** [comment]
Nope
