### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by jizzyjdog** [Dastan21/BDAddons#177]
### Discord Build

Stable

### Discord Version

Stable 174875

### Plugin Version

v1.7.0

### Steps To Reproduce

Select the image section of the plugin

### Describe the bug

Only the image section is having issues. Greyed out boxes overlapping, and when selected they send random pictures previously saved there.
![image](https://user-images.githubusercontent.com/109762133/219824338-5b478015-82e2-4272-b983-56123d56780e.png)

The other sections (video/audio) work and look fine as far as i can tell, but i dont have as many videos/audios saved.

### Screenshots

![image](https://user-images.githubusercontent.com/109762133/219824450-6f0d3d9a-cb72-40c6-b380-3b9602b37d9b.png)

**Comment by Dastan21** [comment]
Duplicate #171
