### ISSUE TITLE
[FavoriteMedia]: No more medias tabs

### ISSUE THREAD

**Issue by Halia-Halation** [Dastan21/BDAddons#179]
### Discord Build

Stable

### Discord Version

175856 (bf85533)

### Plugin Version

1.7.0

### Steps To Reproduce

I , dont really know what had caused this.

### Describe the bug

For some odd reason, i am unsure why but it seems like the plugin has recived a bug where it will not load the files, nor will it show in the buttons in the plug in

**Comment by githubguy217** [comment]
i'm having the same issue, this is what happens when I click on one of the buttons
![image](https://user-images.githubusercontent.com/126123052/220788313-de4c3d64-517a-4ec2-ac5e-2f8ebc68163f.png)

**Comment by critbees** [comment]
Seconded on this issue and the above screenshot from githubguy217^, can no longer see the star button to favourite images or videos now either.

**Comment by LexaWitch** [comment]
Third'd 
Version 1.7.1 here as well. I tested with themes on and off, old and new version, cleared the config json too. Same results as above.

![image](https://user-images.githubusercontent.com/126181685/220951391-8c33ccc8-f130-44cb-9cc1-dd41f03228b4.png)

**Comment by Bozhidar-A** [comment]
Opening the dev tools the images, videos and audio tab seem to bring up the same warning - ```Unable to determine render window for element``` while the normal emoji tab just creates 6 ```[DEPRECATED] Please use `subscribeWithSelector` middleware``` warnings. 

Attempting to find where these warning are thrown just leads to a minified file. Strange.

**Comment by Komrade-Yanouchka** [comment]
yep same issue here

**Comment by IKBxI** [comment]
I do not know nearly enough about js to know if this is the issue, but there is an error at line 2416 :( 
![image](https://user-images.githubusercontent.com/126211680/221059989-918d9e9a-4116-4090-b725-7c45d177fbb7.png)

though the error is in both versions 1.7.0 & 1.7.1

**Comment by bob-carter** [comment]
Also having the same issue, no clue how to post logs or the like for this.

**Comment by OctoRocket** [comment]
I have having this issue as well 
![image](https://user-images.githubusercontent.com/88291550/221390797-1944d23b-4751-43f4-843e-07acdafae8cb.png)

**Comment by Zzeyy** [comment]
I also confirm this to be a real issue

**Comment by kosmaaa** [comment]
would be real cool if you guys stopped saying "hurr i have the same problem durr" and i mean this in the nicest way possible, cheers lads :-)

**Comment by HosenSchisser** [comment]
same issue

**Comment by bob-carter** [comment]
As of 1.7.2 I can now get into the menu, but only via hitting images after opening the Gif button. Still a massive improvement. This said Better Discord is still very unstable for me and everyone else as of the last update 2-3 hours or so ago.

**Comment by bob-carter** [comment]
Update now I can access it normally, no clue why, all that happened was a crash, if you have issue above try fully updating plugin and fully rebooting Discord.

**Comment by Halia-Halation** [comment]
Improvement, it seems like as of late  better discord has been on the fritz, so i had to uninstall it temporarily, altough i assume this may  be a problem on my end. im glad that this may be resolved soon

**Comment by bob-carter** [comment]
Now it seems to cause a crash whenever I right click with this plugin on.

**Comment by Lhinger** [comment]
> would be real cool if you guys stopped saying "hurr i have the same problem durr" and i mean this in the nicest way possible, cheers lads :-)

i also am having this issue

**Comment by Kiq33** [comment]
For clarification: Better Discord is having problems within the last couple of days, crashing every time one would try to open configurations, but FavoriteMedia was broken before that. I fixed the crashing and every other plugin seems to be working fine, except for FavoriteMedia, so I assume it's a plugin problem, not BD.

**Comment by bob-carter** [comment]
With the patch listed in the Betterdiscord server I was using btw.

**Comment by Halia-Halation** [comment]
I suppose now all we can do is wait..

**Comment by bob-carter** [comment]
Seems to have fixed it's self for me, likely the newer update to BD having fixed it.

**Comment by critbees** [comment]
This was also fixed for me with the BD update (:
