### ISSUE TITLE
Suggestion for a potential text tab, and a change to the gif tab

### ISSUE THREAD

**Issue by sighofrelief** [Dastan21/BDAddons#18]
I'd love to see a tab for text, to store copypastas and the like, which i guess could just be the contents of whatever message you favorite (and you could favorite it via that message's dropdown menu, labeled "favorite text" or something of that nature, incase there's also an attatchment. This would also let you include links, so you could technically favorite not only a piece of media, but text to go with it.

As for the gif tab, i'd also love to see the option to disable giphy selection entirely. I honestly never use it, so instead of having to travel through a submenu, favorited gifs are right there in the first page of the gif tab.
Thank you!

**Comment by Dastan21** [comment]
For the first request, I think this plugin does already what you want : https://betterdiscord.app/plugin/PersonalPins.

And for the gif tab I will take a look ;)

**Comment by tort-oise** [comment]
I second the gif tab. Giphy search is probably my least used feature out of every feature on Discord.

**Comment by Dastan21** [comment]
I finally managed to do it. Added in 48dfebe

**Comment by tort-oise** [comment]
Amazing, thank you!
