### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by DeCaffed** [Dastan21/BDAddons#180]
### Discord Build

Stable

### Discord Version

Stable 177136 (f81785f)

### Plugin Version

1.7.2

### Steps To Reproduce

1. Enable Favorite Media.
2. Right click on any message.

### Describe the bug

Right clicking a message causes Discord to crash. Discord will not crash on right click anymore if Favorite Media is disabled.

**Comment by jizzyjdog** [comment]
you need to download the new BD update on their website. this fixed the issue for me. my steps exactly where uninstalling discord, downloading the BD update, reinstalling discord then the new BD
