### ISSUE TITLE
[FavoriteMedia]: Preset Category Thumbnail

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#182]
### Describe the solution you'd like

Preset Category thumbnail.

Image page takes far too long to load when you have a lot, maybe it's because my images are too big or i have too many categories idk.
Maybe have it so when you boot up discord a thumbnail is pre picked for the category and held loaded the same way as for gifs this way it doesn't take too long to load. 
If you wanna put the effort into this too maybe allow picking the image in settings aswell.

This is what discord does for gifs, for the exception of the favorite tab. So for my case the issue is probably that i have too many categories and it has too pick from too many arrays all at once. I'd rather just have a preset thumbnail that is always loaded.

**Comment by Dastan21** [comment]
You can disable categories thumbnail in the medias settings.

**Comment by Dastan21** [comment]
Also thumbnails are loaded after the picker has loaded. What exactly takes time?

**Comment by DeCat4** [comment]
The thumbnails, I have a lot of categories so that's exactly the issue, you load the thumbnails after you load the picker.
An option to have the thumbnails pre-picked would make loading times smaller right? only sacrifice is the images not being random anymore

**Comment by bob-carter** [comment]
Not having them be random would also be great.

**Comment by Aezaeo** [comment]
My FavoritedMedia takes long to load still but not as long as previous builds, it's been improved. I have Hide thumbnails enabled and I also have quite a bit of categories. I personally don't think it's the thumbnails that is the issue for long load times. Some of my categories have 2k+ media saved, I think it's just the sheer volume that I have favorited that results in long load times. That's my experience though.

**Comment by Dastan21** [comment]
Tbh I never tested with that many medias so that may be the issue.

**Comment by DeCat4** [comment]
Any chance this is still getting added?

Also i want to try and explain a little better how the thumbnail system can be improved.

(Now i'm not 100% sure wether or not this is how it works)
From what i see discord has the gifs of each category pre loaded, just not displayed, except for the favorites tab, when you open the picker it displays the gifs and loads in a random image from the favorites tab (it usually takes a little longer for the favorite category thumbnail to load than the others so the other ones were definetly pre loaded)

Pretty much the issue is that discord cannot handle loading 4+ category thumbnails without taking too long, so you need to use discord's method, pick an image upon the boot up of the client, and just display and hide it again whenever the picker is open.

If you want to keep the option to randomize the image for each category, maybeee give it a try to randomly select a different image for the thumbnail after you leave the picker tab, when you open it next time the newly chosen image is gonna be already loaded.

**Comment by Dastan21** [comment]
Added in v1.10.0.
