### ISSUE TITLE
[FavoriteMedia]: Images in category failing to load

### ISSUE THREAD

**Issue by bob-carter** [Dastan21/BDAddons#183]
### Discord Build

Stable

### Discord Version

Stable 178236 (c4c6e71)

### Plugin Version

1.7.2

### Steps To Reproduce

Run discord, add or open existing category for saved images, all images are bugged out.

### Describe the bug

None of the image previews for images in categories load, from time to time one or two will still load, but that's it. I checked and the config has image sizes for width and height for all images. Newly placed images into said places also have this issue.

They also seem to have heights and and clipping issues. Again all images in config have listed values.

### Screenshots

![Screenshot 2023-03-03 153506](https://user-images.githubusercontent.com/46971019/222761672-a9025ed9-34df-413b-9bbb-cf1c29542e85.png)

**Comment by bob-carter** [comment]
Update, after deleting my settings config for the plugin (with discord task terminated), the issue seems to be gone for now. I backed it all up and readded all my images manually (minus the Gifs that it saves for some reason) and now it's currently working. No clue if the gifs were causing it or not, or the MP3's I also didn't add back, was already kinda tedious to do so didn't bother.

**Comment by bob-carter** [comment]
Another update, now it randomly doesn't show more then 1 or 2 images in the images tab. Categories in said tab seem unaffected.

**Comment by AManNamed2** [comment]
Also getting this 
![image](https://user-images.githubusercontent.com/50536667/222928425-5373cf0d-6e14-4b3a-93d8-a4f8d7507cbb.png)

**Comment by BloodGozilla** [comment]
i am having the same issue
