### ISSUE TITLE
[FavoriteMedia]: Crash BetterDiscord with Newest Build 1.7.2

### ISSUE THREAD

**Issue by Aezaeo** [Dastan21/BDAddons#184]
### Discord Build

Stable

### Discord Version

Stable 178236 (c4c6371)

### Plugin Version

1.7.2

### Steps To Reproduce

Update to FavoriteMedia to 1.7.2 
Launch BetterDiscord 
BetterDiscord Hangs Loading media from a server then crashes.

### Describe the bug

BetterDiscord Crashes after updating to 1.7.2 build of FavoriteMedia. The Console Error is: "<link rel=preload> uses an unsupported `as` value". If I comment out line 2402 in the code: "link.rel = 'preload'". BetterDiscord will no longer crash.

### Screenshots

![Discord_59EuHXeoWw](https://user-images.githubusercontent.com/24560181/222771818-5b467b3e-5d29-47ab-bc3c-b536ac2fc996.png)

**Comment by Dastan21** [comment]
Removed in 1.7.3
