### ISSUE TITLE
[FavoriteMedia]: breaks the use of the letter "m" in chat input

### ISSUE THREAD

**Issue by Ao1Pointblank** [Dastan21/BDAddons#185]
### Discord Build

Stable

### Discord Version

Stable 178590 (6d3ed59)

### Plugin Version

1.7.2

### Steps To Reproduce

Environment: Linux Mint 21.1 x64 w/ Cinnamon 5.6.7, window manager Mutter, X11
1) Install the plugin
2) switch apps, move to another workspace, or maybe just wait a minute. 
3) the m key will not be able to type in Discord. Shift + m still works to type M, and other apps work fine
3) reload discord to fix issue temporarily
4) alternatively, temporarily fix the issue by toggling the window's maximization state

### Describe the bug

the m key breaks soon after enabling this plugin.
I reinstalled the plugin and had it create a new config but the problem persisted.
If I knew how to get useful logs, I would be happy to supply them but I will need to be walked through that process.

here is my config:
```
{
    "currentVersionInfo": {
        "version": "1.7.2",
        "hasShownChangelog": true
    },
    "settings": {
        "hideUnsortedMedias": false,
        "hideThumbnail": false,
        "alwaysUploadFile": true,
        "alwaysDeleteDeadMedias": false,
        "disableMediasTabKeybind": true,
        "alwaysSendUpload": "none",
        "mediaVolume": 10,
        "position": {
            "btnsPosition": "right",
            "btnsPositionKey": "emoji"
        },
        "gif": {
            "enabled": true
        },
        "image": {
            "enabled": true,
            "showBtn": false,
            "showStar": true
        },
        "video": {
            "enabled": true,
            "showBtn": false,
            "showStar": true
        },
        "audio": {
            "enabled": true,
            "showBtn": false,
            "showStar": true
        }
    }
}
```

**Comment by Dastan21** [comment]
Fixed in 1.8.0 (new keybinds: CTRL+ALT+I/V/A
