### ISSUE TITLE
[FavoriteMedia]: Favorite Links/Messages

### ISSUE THREAD

**Issue by LeaLangley** [Dastan21/BDAddons#186]
### Describe the solution you'd like

Hello there , i love this plugin , its probably my fav plugin and it is 1:1 what i was dreaming of discord should have.
anyways , i would love to see a option to save Links and/or Messages.

for example:
i want to send my friends a spotify playlist they like and let them know ive updated it.
or (favorite Messages)
i want to send a download link for something and add a small explanation how to use it.

maybe these are bad examples but i see alot of potential in it , specially if you have forgetful friends as i do and i need to send them more often the download link for something.

**Comment by Dastan21** [comment]
The plugin [PersonalPins](https://betterdiscord.app/plugin/PersonalPins) already does that.

**Comment by LeaLangley** [comment]
its not working for files

**Comment by Dastan21** [comment]
Just pin the message which files are attached to?

**Comment by LeaLangley** [comment]
yea i can do that , but i cant copy/send it into any chat, if i press copy its empty too

**Comment by LeaLangley** [comment]
maybe a option to favorite files like , txt , pdf , zip , rare , bat , exe and etc.

**Comment by Dastan21** [comment]
I'll keep this issue open, but cannot promise it will be implemented.

**Comment by LeaLangley** [comment]
i appreciate it , and your work in general , its an amazing plugin that convinced a friend who was against better discord to download it^^

**Comment by Dastan21** [comment]
Added new medias type `file` in v1.10.0.
