### ISSUE TITLE
[FavoriteMedia]: Images tab fails to put images one after another, instead putting them on top of each other

### ISSUE THREAD

**Issue by Bozhidar-A** [Dastan21/BDAddons#188]
### Discord Build

Stable

### Discord Version

Stable 178850 (ce63c6e)

### Plugin Version

v1.7.2

### Steps To Reproduce

1. Favorite an image
2. Favorite another image

### Describe the bug

After favoriting one image we can see it. [img 1] Favoriting another hides the first. [img 2] We can only see it by removing the second image. Ignore the example images these the first in my chat

### Screenshots

img 1
<img width="376" alt="image" src="https://user-images.githubusercontent.com/62239520/223575810-1096fc76-752d-4b7f-bdbd-924484c52303.png">

img 2
<img width="377" alt="image" src="https://user-images.githubusercontent.com/62239520/223575968-89acb92c-63fb-4be8-9394-dbb8947b53e0.png">

**Comment by jizzyjdog** [comment]
same, i think everyone has this issue right now

**Comment by Dastan21** [comment]
Duplicate #171
