### ISSUE TITLE
[FavoriteMedia]: dropdown menu for "buttons relative position" setting is cut off

### ISSUE THREAD

**Issue by staticanimal** [Dastan21/BDAddons#190]
### Discord Build

Stable

### Discord Version

Stable 179619 (02dd321)

### Plugin Version

1.7.2

### Steps To Reproduce

1. go to favoritemedia's plugin settings in betterdiscord
2. open "buttons relative position" dropdown menu

### Describe the bug

the dropdown menu for the "buttons relative position" setting is cut off at the bottom as a result of it overlapping with the "gif settings" menu 

### Screenshots

https://s1.fileditch.ch/iwguQJYeFonIgFzBbknx.png

**Comment by Dastan21** [comment]
Related to https://github.com/rauenzi/BDPluginLibrary/issues/194

**Comment by Dastan21** [comment]
Fixed in v1.12.0+
