### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by ChilledReCoded** [Dastan21/BDAddons#191]
### Discord Build

Stable

### Discord Version

Stable 178850 (ce63c6e)

### Plugin Version

1.7.2

### Steps To Reproduce

1. Open 'Image' Tab
2. With standard, unchanged settings

### Describe the bug

Images on the image tab do not load properly and neither do folders. 
The box to upload the image is still there, but the image itself is not.

**Comment by bob-carter** [comment]
Open the file in Notepad++ and replace all "100%" with 300. Fixes it for me at least.

**Comment by soulshot96** [comment]
Same issue here. replacing 100% with 300% makes the top row selectable, albeit with some visual issues, but I cannot scroll or access any images beyond the top row.

**Comment by Dastan21** [comment]
Update to 1.7.3 and https://github.com/Dastan21/BDAddons/issues/109#issuecomment-1219146067
