### ISSUE TITLE
[FavoriteMedia]: Can't even describe this

### ISSUE THREAD

**Issue by Zzeyy** [Dastan21/BDAddons#193]
### Discord Build

Stable

### Discord Version

Stable 181832 (ee303b2)

### Plugin Version

1.7.2

### Steps To Reproduce

1. Open the image tab
2. See the bug

### Describe the bug

The "whatever that thing is" thing in the middle is blocking the images.

### Screenshots

![image](https://user-images.githubusercontent.com/97387354/226334342-595a6d1b-fdd8-4ea8-b7c2-49033b1d5bf1.png)

**Comment by Dastan21** [comment]
Open FavoriteMedia.config.json, search for medias that have width: "100%" (or at least not number), unfavorite them, update to [1.7.3](https://raw.githubusercontent.com/Dastan21/BDAddons/2ec20c820e7b7e0696a8d45ce9977dfb58418fff/plugins/FavoriteMedia/FavoriteMedia.plugin.js) (copy/replace to FavoriteMedia.plugin.js) and refavorite them.

**Comment by Zzeyy** [comment]
This solution is way too complicated, considering the fact that the amount of favorite media isn't low at all.

**Comment by Dastan21** [comment]
Take it or leave it I won't do more.

**Comment by Zzeyy** [comment]
Oh, I'm outdated

**Comment by Zzeyy** [comment]
Screw BetterDiscord and its update system

**Comment by Zzeyy** [comment]
Updating solves most of the issue, I thought I'd have to favor most of the media again
