### ISSUE TITLE
[FavoriteMedia]: Upload as file options per type

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#194]
### Describe the solution you'd like

Options to select wether or not Images,Videos,Audios,Gifs will get sent as links or files.

Would be nice to choose for audios & videos to upload as files since i'm fine with them uploading slowly
(discord only hides the links if it's images)

**Comment by Dastan21** [comment]
Added in 1.8.0 (moved "always send instant" & "always upload file" settings per media)
