### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by Komrade-Yanouchka** [Dastan21/BDAddons#195]
### Discord Build

Stable

### Discord Version

181873 (5cb853d)

### Plugin Version

v1.7.2

### Steps To Reproduce

open the image tab

### Describe the bug

in the image tab images are placed randomly some are overlapping, some not rendering and there's empty spaces in the middle of the list.

### Screenshots

![Capture](https://user-images.githubusercontent.com/68874488/226939914-997e1677-45fc-4c98-9a57-8bfba32de8f7.PNG)
![image_2023-03-22_154119004](https://user-images.githubusercontent.com/68874488/226940017-6b5c4164-0311-436e-a401-b8efa7af5200.png)

**Comment by Dastan21** [comment]
Update to 1.7.3 and https://github.com/Dastan21/BDAddons/issues/109#issuecomment-1219146067

**Comment by Komrade-Yanouchka** [comment]
ah my bad
