### ISSUE TITLE
[FavoriteMedia]: Discord crashes when opening

### ISSUE THREAD

**Issue by Minepool9** [Dastan21/BDAddons#196]
### Discord Build

Stable

### Discord Version

Stable 179882 (d4bc856)

### Plugin Version

Version 1.7.2

### Steps To Reproduce

i do not know

### Describe the bug

Literally trying to open better discord with this makes the enitre thing die

**Comment by Dastan21** [comment]
Update to 1.7.3 then retry

**Comment by ChilledReCoded** [comment]
It happens with 1.7.3 as well, cause I'm having the same issue.

**Comment by ronfino** [comment]
Yep

**Comment by Dastan21** [comment]
Caused by BetterDiscord, not the plugin: https://github.com/BetterDiscord/BetterDiscord/issues/1583
