### ISSUE TITLE
[FavoriteMedia]: Option to replace trending gif categories with custom ones

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#197]
### Describe the solution you'd like

Would be nice to have favorites just be a category on it's own and be able to create other gif categories in the gif page, make this a separate option, it would remove discord's trending gifs and all that so you can have space for your own categories. This way any categories under favorites are sub categories

**Comment by Dastan21** [comment]
I don't really understand how it would be useful since you can create sub-categories within the GIFs favorites folder. And the main problem would be: how do you search for new GIFs, since the search bar would have to filter favorites/categories names tho

**Comment by DeCat4** [comment]
For the search bar you can have an option to change it from search tenor to search folders and it would search all the folders you have in the gif tab.

As for why it would be useful plenty of people find the random trending gifs and other gif pages useless, it would make it generally more convenient and organized if those could be replaced with categories of your own, less clicks and less loading time.
Perhaps this can lead to some optimization if you are able to unload all the tenor gifs preloaded for display

It would just make the GIF tab fit in with the others since that's how they work unless i worded myself the wrong way but tldr i'm just suggesting that the GIF page has an option to work the same as the other pages

**Comment by Dastan21** [comment]
Won't add, there are too many issues for what it's worth.
