### ISSUE TITLE
[FavoriteMedia]: images on top of eachother and invisible

### ISSUE THREAD

**Issue by FroggyRaven** [Dastan21/BDAddons#199]
### Discord Build

Stable

### Discord Version

Stable 186981

### Plugin Version

1.7.3

### Steps To Reproduce

open the image button next to the emoji button

### Describe the bug

all the images are overlayed on top of eachother/invisible

### Screenshots

![Screenshot_2050](https://user-images.githubusercontent.com/85956701/230247131-e8326e77-17b6-4d14-9ec0-cdf652bc3eb6.png)

**Comment by helpme69420** [comment]
Same issue

**Comment by Jackylacky162** [comment]
same issue here too

**Comment by Dastan21** [comment]
https://github.com/Dastan21/BDAddons/issues/109#issuecomment-1219146067, by "reset" I mean, unfavorite then favorite again

**Comment by Jackylacky162** [comment]
is there way we can reset every image because I kinda have much of them?

**Comment by Jackylacky162** [comment]
is there way I can reset all images because in my case its so bugged i cant even un-fav?

**Comment by Jackylacky162** [comment]
thanks

**Comment by Jackylacky162** [comment]
Doesn't work for me is there way I can just reset whole plugin bc re-downloading and deleting cfg file does nothing

**Comment by FroggyRaven** [comment]
alr. thanks
