### ISSUE TITLE
[FavoriteImageVideo] Weird tabs behaviour

### ISSUE THREAD

**Issue by dav1312** [Dastan21/BDAddons#2]
When clicking the original buttons the tab doesn't need to reload, it just changes betweet them.
When clicking the image and video buttons the entire tab disapears and appears again and that seems to cause some problems (end of the video)

https://user-images.githubusercontent.com/63931154/106372630-c73c3c80-6371-11eb-911c-426b40f23580.mp4

**Comment by Dastan21** [comment]
Fixed in https://github.com/Dastan21/BDAddons/commit/e13417d0f268816ab8d9ae478c7dcd3dab84c19e
