### ISSUE TITLE
[FavoriteMedia]: Categories settings not opening

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#202]
### Discord Build

Stable

### Discord Version

Stable 201332 (10d1e45)

### Plugin Version

1.8.0

### Steps To Reproduce

Go to plugin settings
Click on the settings for image or anything bellow
nothing happens except arrow moves

### Describe the bug

Can't use the settings for images or anything bellow.

I just downloaded 1.8.0 by replacing the javascript file in plugins and now the settings for images and lower doesn't work and i'm stuck with the old settings.

### Screenshots

![Capture](https://github.com/Dastan21/BDAddons/assets/57727851/50504edc-e157-4e6d-ba07-15b4b8f4624d)

**Comment by Dastan21** [comment]
ZLibrary error

**Comment by DeCat4** [comment]
Any way i can fix this or i have to wait for zlibrary to fix it's issues?

**Comment by Dastan21** [comment]
Wait for a fix, you can report it on his repo
