### ISSUE TITLE
[FavoriteMedia]: Can't write ' @' symbole when FM is activate !

### ISSUE THREAD

**Issue by Adam935** [Dastan21/BDAddons#203]
### Discord Build

Stable

### Discord Version

202327 (c8c7d2d)

### Plugin Version

v1.8.0

### Steps To Reproduce

I'm on Windows. 

1- Activate the plugins

2- Go where u want on discord like channel, DM ect...

3- Try to write a '@' symbole 

4- Here you should see the '@' symbol on your discord but it's not showing.

### Describe the bug

Here you should see the '@' symbol on your discord but it's not showing.

**Comment by Dastan21** [comment]
Windows, Mac or Linux?

**Comment by Adam935** [comment]
Windows

**Comment by Dastan21** [comment]
Only @ or some others characters too?

**Comment by Adam935** [comment]
> Only @ or some others characters too?

sry didn't see your message, to my knowledge only that yes.
moreover I took an old version so currently I am on version 1.7.3 it works well, I test all later versions it does not work so i guess it's a problem between 1.7.3 and 1.7.4.

**Comment by Dastan21** [comment]
Removed keybinds in 1.8.2
