### ISSUE TITLE
[FavoriteMedia]: Can't paste media to chat

### ISSUE THREAD

**Issue by BotThrusther** [Dastan21/BDAddons#205]
### Discord Build

Stable

### Discord Version

Stable 204204 (942e9ba)

### Plugin Version

1.8.1

### Steps To Reproduce

1. open gifs, image, video or audio
2. let image load
3. click on selected media
4. not pasting to chat

### Describe the bug

With the new update to add pages to the media tabs, can no longer paste any images, gifs, video or audio to chat anymore

**Comment by Dastan21** [comment]
Pushed a hotfix, waiting for BD approval. You can replace it manually from here https://github.com/Dastan21/BDAddons/blob/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js

**Comment by Nama** [comment]
I needed to manually disable and enable the plugin again so it works (after deleting and putting the hotfix in).

Same for the setting "Replace discords GIF Tab".
