### ISSUE TITLE
[FavoriteMedia]: Unable to favorite medias and open FavoriteMedia context menu, causing list-lock.

### ISSUE THREAD

**Issue by ronfino** [Dastan21/BDAddons#206]
### Discord Build

Stable

### Discord Version

Stable 204204 (942e9ba)

### Plugin Version

1.8.1

### Steps To Reproduce

**Bug 1 - Unable to favorite medias**
1. Right click on GIF/video/image/audio
2. Bug encountered. Lacks FavoriteMedia's voices.

**Bug 2 - Unable to open FavoriteMedia context menu and list-lock.**
1. Left click on GIF/video/image/audio icon to open the favorited media list
2. Right click on any media or a category.
3. Bug encountered. A context menu won't pop up and the favorited media list will be sort-of-like locked until i left/right click the GIF/video/image/audio icon.

### Describe the bug

Pretty much what i said above. Do note though that the bug occurred after ZeresPluginLibrary received an update that would "fix" the dropdown settings issue. The bug did got fix but now it seems to have made a new one. I believe this is related to the problem i reported here.

### Screenshots

**First bug**
![image](https://github.com/Dastan21/BDAddons/assets/77462428/72937417-c762-4def-b212-df1649444b87)

**Second bug**
https://i.gyazo.com/6f29aa8e6f59ac25330453d02b67e40a.mp4

**Comment by Dastan21** [comment]
https://github.com/BetterDiscord/BetterDiscord/issues/1631, now we are waiting for the next version release

**Comment by ronfino** [comment]
@Dastan21 Despite upgrading to the next version the issue still persists.

**Comment by Dastan21** [comment]
The version is not out yet

**Comment by ronfino** [comment]
Oh, i've seen FavoriteMedia receiving an upgrade yesterday, that's why i said that.
