### ISSUE TITLE
[FavoriteMedia]: Click outside to close

### ISSUE THREAD

**Issue by Moo2meenn** [Dastan21/BDAddons#207]
### Discord Build

Canary

### Discord Version

Canary 204459 (2ebe741)

### Plugin Version

FavoriteMediav1.8.1

### Steps To Reproduce

Just open the Media window and try to click outside, it will not close the window

### Describe the bug

In the default Discord's GIF/Stickers/Emojis menu, when you click outside, it closes the window. But with FavoriteMedia, it does not close it no matter what you click, and I cannot find the option to disable that.
Sorry if I am just blind and there is actually an option for that

**Comment by Dastan21** [comment]
what was it?

**Comment by Moo2meenn** [comment]
It was my Discord just being stupid, I restarted it and it started working
