### ISSUE TITLE
[FavoriteMedia]: Cannot send images or gifs anymore at all.

### ISSUE THREAD

**Issue by jizzyjdog** [Dastan21/BDAddons#208]
### Discord Build

Stable

### Discord Version

Stable 204204 (942e9ba)

### Plugin Version

1.9.2

### Steps To Reproduce

1. open the plugins popup
2. try to click an image

### Describe the bug

I cannot send images, gifs, videos, or anything anymore apparently since the new update. I click it repeatedly, nothing. I try to right click and send manually, nothing. Here is a video, in which I both click AND right click, nothing happens.
![opera_aqiVoqFuXc](https://github.com/Dastan21/BDAddons/assets/109762133/7ddf9667-f07d-4871-8bad-d6448515b7d8)

**Comment by Dastan21** [comment]
Duplicate #205
