### ISSUE TITLE
Question about reinstalling BetterDiscord and keeping favorited media

### ISSUE THREAD

**Issue by Zagreus12** [Dastan21/BDAddons#21]
BetterDiscord is crashing and I have decided that I should delete all my plug-ins and reinstall BetterDiscord. Before I do that, I want to save the videos, images, etc. that I have favorited using this plug-in. 

Can I find the files saved to my computer somewhere? (I'm guessing not)

Is there a file(s) that saves the data in a way that if I deleted the plug-in, I could keep my favorited media favorited on Discord itself?

And finally. If I delete the plug-in does the favorited media remain favorited somehow? (I'm guessing that's a no)

If anyone knows what I can do to save or keep my favorited media please tell me.

**Comment by Dastan21** [comment]
There is indeed a file which saves locally every link of image/video/audio. This file is the config file in the plugins folder : `FavoriteMedia.config.json`.
I'm working on a way to download every media to our computer.

**Comment by Dastan21** [comment]
Hi again, you can now download images, videos and audios locally by clicking on the save button :
1. Save medias one by one
2. Save every media of a category (it creates a folder with the name of the category)
