### ISSUE TITLE
[FavoriteMedia]: right click options not working

### ISSUE THREAD

**Issue by LeSprongle** [Dastan21/BDAddons#210]
### Discord Build

Stable

### Discord Version

Stable 205372 (17fac41)

### Plugin Version

v1.8.2

### Steps To Reproduce

go to image section
right click on an image or category
options dont show up

### Describe the bug

when right clicking on an image or category instead of the options showing up nothing happens

**Comment by Dastan21** [comment]
Context menus are disabled cuz they crash Discord, wait for the next BD version

**Comment by LeSprongle** [comment]
oke thank you
