### ISSUE TITLE
[FavoriteMedia]: Import config.json

### ISSUE THREAD

**Issue by othello777** [Dastan21/BDAddons#212]
### Describe the solution you'd like

A way to import a FavoriteMedia.config.json favorites database into an existing one to merge them.

Since there is no way to sync between separate clients, it would be nice to be able to import/merge my config from my machines with each other to periodically update the favorite library. 

Another use would be if someone lost their config, and started favoriting stuff and now wants to import their old config from a backup.

**Comment by misterpyrrhuloxia** [comment]
+1 - this would be awesome

**Comment by Dastan21** [comment]
Added medias/categories import in v1.10.0.
