### ISSUE TITLE
[FavoriteMedia]: Red X Video Thumbnails

### ISSUE THREAD

**Issue by tavvvvvvvvvvvvvv** [Dastan21/BDAddons#213]
### Discord Build

Stable

### Discord Version

Stable 215587 (bf26f2b)

### Plugin Version

1.8.4

### Steps To Reproduce

Favorite a video
Look at the thumbnail

### Describe the bug

If you favorite a video and select the picker you see the thumbnails are all red X's.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/138950887/47cff9b1-5742-49da-8eee-f245beaed2bd)

**Comment by RDP8** [comment]
Same issue here, and it's very frustrating.

**Comment by Dastan21** [comment]
Do you have "Uncompressed Images" plugin?

**Comment by RDP8** [comment]
> Do you have "Uncompressed Images" plugin?

Yes, I do, I turned it off, and 90% of them are still red Xs.

**Comment by Dastan21** [comment]
Should be fixed in 1.8.5 + UncompressedImages 3.15
