### ISSUE TITLE
[FavoriteMedia]:Favourited  Media are big regardless of the menu size and the page button is missing.

### ISSUE THREAD

**Issue by TheConfusedlol** [Dastan21/BDAddons#215]
### Discord Build

Stable

### Discord Version

Stable 218051 (4a59b3c)

### Plugin Version

1.8.4

### Steps To Reproduce

1: Enable plugin
2:Go into any  menu
3:See their expanded size and lack of a page button

### Describe the bug

Whenever i go into any of the other media tabs and the favourites section of the gif tab, not only are the images, videos and gifs always huge no matter how wide i set the gif window, I also don't see a page button.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/69022214/5594abeb-2650-4221-ac69-12bfd34a43d4)

**Comment by Jdbaii** [comment]
Can confirm. New Discord update seems to have broken it. I really liked having the favorites separated into pages (great feature that must've been added in a semi recent update without me noticing), but currently I can only see the first page of my favorites. Had to turn the plugin off just to see the rest of them.
This is one of my favorite plugins currently, so I hope it gets fixed soon. Being able to favorite pictures the same way you can favorite gifs and easily post them as reactions makes so much sense and is such a nice feature, I don't know why Discord ever limited this to just GIFs to begin with?
Plus the quality of life improvements on top of that, like the pagination, are an added bonus.

**Comment by TheConfusedlol** [comment]
You can still have the plugin on while being able to see all your gifs, you can turn off the alternate menu in the settings. 
![image](https://github.com/Dastan21/BDAddons/assets/69022214/b1565e98-ff53-4a9b-9c92-46f450ed0f3f)

**Comment by Jdbaii** [comment]
> You can still have the plugin on while being able to see all your gifs, you can turn off the alternate menu in the settings. ![image](https://user-images.githubusercontent.com/69022214/258646032-b1565e98-ff53-4a9b-9c92-46f450ed0f3f.png)

Ahh, thank you. That helps a lot.

**Comment by MahdeenSky** [comment]
+1

**Comment by Dastan21** [comment]
Still bugged?
