### ISSUE TITLE
[FavoriteMedia]: Buttons to switch page not appearing

### ISSUE THREAD

**Issue by AidanPlayz3310** [Dastan21/BDAddons#216]
### Discord Build

Stable

### Discord Version

Stable 218604 (958c14c)

### Plugin Version

1.8.4

### Steps To Reproduce

Just trying to look through my media at all, on any media type.

### Describe the bug

The page numbers or arrows will not appear for me even though I have more than 50 things favorited. I also tried to turn off my themes and other plugins and that still did not fix it.

### Screenshots

![Discord_KpDEHGOp7T](https://github.com/Dastan21/BDAddons/assets/67774956/48800662-3d3f-4683-a95f-1b0cb3aa00f2)

**Comment by nitolar** [comment]
I have the same issue
![obraz](https://github.com/Dastan21/BDAddons/assets/73779998/ce9ebeef-ba1d-4ca0-8ce7-17f0898653bf)
![obraz](https://github.com/Dastan21/BDAddons/assets/73779998/a75ba594-8326-4b6e-b3e5-330214d4b581)

**Comment by Dastan21** [comment]
Fixed in 1.8.5
