### ISSUE TITLE
[FavoriteMedia]:  RED X THUMBAIL / DEAD VIDEO/IMAGE LINKS 

### ISSUE THREAD

**Issue by unsrve** [Dastan21/BDAddons#217]
### Discord Build

Stable

### Discord Version

Stable 222511 (59b1a70)

### Plugin Version

v1.8.5

### Steps To Reproduce

1. favorite a vid/image
2. after a few days it stops being a valid image/vid to send ( red x thumbnail ) 

### Describe the bug

happens to me all the time, started doing this like after a week of using this plugin. i really like using this plugin and i hate it when it removes the videos/pictures i wanna send. ( i go in any channel, press the media button. see a red X thumbnail and when i click to send it it sends a dead link.) happends only with images and videos. 

### Screenshots

![1](https://github.com/Dastan21/BDAddons/assets/38105459/d6475011-0d3a-433b-982c-53ce049c1e35)
![2](https://github.com/Dastan21/BDAddons/assets/38105459/655f3e3f-a526-4a5b-99a9-cd9c7a0b630a)

**Comment by Dastan21** [comment]
Do you have UncompressedImages? A fix has been made for v3.15

**Comment by Dastan21** [comment]
To test if the red crosses are legit, copy the media link (right-click on media + "copy media link") and paste it in the browser, if it shows a page with text (xml) it's normal, otherwise if it downloads the video / shows the image then the "dead media" system is wrong

**Comment by unsrve** [comment]
**tried one with a image and it sent this**
![1](https://github.com/Dastan21/BDAddons/assets/38105459/c86f3501-f5e0-4df7-837e-d9b0d1ac4b3c)


**now this one is one of my videos that had a X mark aswell**
![2](https://github.com/Dastan21/BDAddons/assets/38105459/41b57ec2-43a5-4d72-86f9-97fa271f80c5)

**Comment by Dastan21** [comment]
so it's normal, the original msgs were deleted

**Comment by unsrve** [comment]
theres no fix to this? and it only saves messages that people dont delete? for example : if someone sent a vid or image in chat and i saved it thru the media plugin of urs. it will stay iin there working. but if they **deleted** the msg where they sent the video/image. it shows the RED X ?

**Comment by Dastan21** [comment]
Discord caches a few days a media after the original post has been deleted. This plugin just keeps media links. If tout want to keep medias forever, you have to ensure the msgs don't get deleted : example upload them in a private server

**Comment by unsrve** [comment]
i was thinking of that aswell. thanks !
