### ISSUE TITLE
[FavoriteMedia]: Category-related display issues (at least with GIFs)

### ISSUE THREAD

**Issue by vii0ne** [Dastan21/BDAddons#218]
### Discord Build

Stable

### Discord Version

223831

### Plugin Version

1.8.5

### Steps To Reproduce

- _You must create a category for these issues to occur_

**Situation A1 (Search acts weird)**
1. Go to any page except the first one
2. Search for anything
3. Number of results shows in top right, no GIFs are actually displayed
4. This can be mitigated by ensuring you're on the first page before searching
     - Situation B still makes it difficult to add GIFs to categories unless you know what to search for all of them

**Situation A2 (Pagination acts weird)**
1. Navigate through pages after creating at least one category
2. Results do not display on quite the same pages, which may be a result of Situation B

***
**Situation B (Last GIFs in the favourites list are not displayed)**
1. Optionally add GIFs to a category
3. GIFs at the very end of the favourites list are not displayed (for me, it starts with 2 being hidden after creating one category)
6. The more GIFs added to categories, the more GIFs at the end that are not visible

### Describe the bug

GIFs don't show up in search, only when at least one category exists.
GIFs at the very end of the favourites list don't display in a similar manner, beginning with one category. The more categories/GIFs added to categories, the more GIFs that don't show at the end.
Being able to sort by ascending/descending date added could help with this if there isn't a good fix otherwise. It somehow actually did sort sort it in reverse order once, but I have no idea how and it reverted itself after a little while.

This issue is particularly unfortunate since it defeats the usefulness of one of the larger parts of this plugin: Using categories. I hope you can find a fix.
Some minute details of this might be absent since it's just so funky to work with.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/63260365/9d99404b-61cb-4725-88af-2d3e1fadc0b6)
When no categories are created. Note that there is no scrollbar; these are the only three GIFs on this last page.

![image](https://github.com/Dastan21/BDAddons/assets/63260365/daaa6e3c-ce4c-4e3e-ab8e-4e18f46d8de9)
After one category is created. There is a scrollbar, this is at the very bottom of the page. The last two GIFs in the favourites list as seen in the first image are no longer present.

**Comment by Dastan21** [comment]
Thanks for your detailed report. This has been fixed in v1.8.6.
