### ISSUE TITLE
Chinese(Taiwan) translation fix

### ISSUE THREAD

**Issue by JimLi999** [Dastan21/BDAddons#22]
[FavoriteMedia_Chinese(Taiwan) translation fix.txt](https://github.com/Dastan21/BDAddons/files/7012267/FavoriteMedia_Chinese.Taiwan.translation.fix.txt)

**Comment by Dastan21** [comment]
Are you sure it is working ?

From VSCode :
![image](https://user-images.githubusercontent.com/58090137/130025205-8067a5f9-31d6-44df-a1fa-33a16cd0c198.png)

From NotePad :
![image](https://user-images.githubusercontent.com/58090137/130025280-baaafedd-e763-4517-8114-63d40a3b6967.png)

**Comment by JimLi999** [comment]
[FavoriteMedia_Chinese.Taiwan.translation.fix.txt](https://github.com/Dastan21/BDAddons/files/7013944/FavoriteMedia_Chinese.Taiwan.translation.fix.txt)
(UTF-8)

**Comment by Dastan21** [comment]
Thanks! Will be fixed in the next update.

**Comment by JimLi999** [comment]
Thanks for this good plugin
