### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by metameta2** [Dastan21/BDAddons#221]
### Discord Build

Stable

### Discord Version

Stable 227949 (31c628d)

### Plugin Version

1.8.7

### Steps To Reproduce

1- I downloaded this pluging
2- An error was encountered while trying to load this plugin.

### Describe the bug

It's not working.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/55445749/a9d040df-8370-4bb4-91cf-5665aa54bdbb)

**Comment by Dastan21** [comment]
Duplicate #220

**Comment by metameta2** [comment]
solved thanks
