### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by KlintGit** [Dastan21/BDAddons#222]
### Discord Build

Stable

### Discord Version

Stable 228672 (e9ebae8)

### Plugin Version

1.8.8

### Steps To Reproduce

No steps required

### Describe the bug

As of the recent Discord update listed, the plugin no longer works properly as in I can no longer send the images, videos, sounds, and gifs I have favorited. I can still download the media that I have favorited in the menu, but this should still be looked into.

**Comment by Dastan21** [comment]
Is this still an issue?
