### ISSUE TITLE
[FavoriteMedia]: Can't upload video.

### ISSUE THREAD

**Issue by AlphaGaming7780** [Dastan21/BDAddons#226]
### Discord Build

Stable

### Discord Version

Stable 238545 (dd9e385)

### Plugin Version

1.8.9

### Steps To Reproduce

1. Enable Upload instead of sending the link.
2. Try to send a fav video in a chat.

### Describe the bug

The video won't upload when we enable uploading instead of sending the link.

**Comment by AlphaGaming7780** [comment]
It's a BetterDiscord bug ?

**Comment by Dastan21** [comment]
Discord removed a module I use, BD will remake it.

**Comment by AlphaGaming7780** [comment]
Ohh, Okay, so we just have to wait.
Thanks for your time.

**Comment by Dastan21** [comment]
Fixed in BD 1.9.4
