### ISSUE TITLE
[FavoriteMedia]: plugin not working anymore

### ISSUE THREAD

**Issue by minnieoo** [Dastan21/BDAddons#227]
### Discord Build

Stable

### Discord Version

Stable 240884 (d20955f)

### Plugin Version

1.9.5

### Steps To Reproduce

1. open discord
2. enable favoritemedia 

### Describe the bug

the plugin no longer works, presumably since the better discord 1.9.5 update, but not sure. not sure if it uses zerespluginlibrary, but that also doesnt work now so it could be that

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/137783738/47040254-cee5-4f20-b31b-d8e2bd989fe9)
![image](https://github.com/Dastan21/BDAddons/assets/137783738/f854b387-3672-4169-8821-579a61b59ac3)
![image](https://github.com/Dastan21/BDAddons/assets/137783738/28549b41-ae23-410e-ac17-df38262fcfdf)
![image](https://github.com/Dastan21/BDAddons/assets/137783738/ec1cd2fa-82cb-434d-9bd8-ffdb43674f8f)

**Comment by BloodGozilla** [comment]
Yeah it is currently not working anymore.

**Comment by Dastan21** [comment]
I'm working on a fix

**Comment by Dastan21** [comment]
Fixed in 1.8.11
