### ISSUE TITLE
[FavoriteMedia]: Conflicts with ImageUtilities by DevilBro

### ISSUE THREAD

**Issue by Reibies** [Dastan21/BDAddons#228]
### Discord Build

Stable

### Discord Version

Stable 242566 (12901f7)

### Plugin Version

v1.8.11

### Steps To Reproduce

1. Have ImageUtilities and Favorite Media both toggled on
2. Upload an image
3. Use ImageUtilities "Save Image as..." feature
4. Receive thumbnail version of the original

### Describe the bug

When using FavoriteMedia is disabled ImageUtilities functions as expected after it updated recently but with FavoriteMedia on I am receiving images that are cropped and lower quality.

I'll also say when favoriting an image I wind up with the cropped thumbnail as well. Clciking it and uploading still outputs the proper image but if I favorited an image that was in a batch I will only see a cropped portion.

If I am to also bring this up over on the mwittrien repo I can.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/5918813/ae97451f-f773-440b-bb7f-067ec6202a73)
![image](https://github.com/Dastan21/BDAddons/assets/5918813/7f4457b0-323d-4ce6-baec-3f75ee8f652a)

**Comment by Dastan21** [comment]
Fixed in 1.8.12
