### ISSUE TITLE
[FavoriteMedia]: add option to minimize amount of chatbar buttons

### ISSUE THREAD

**Issue by Megalodab** [Dastan21/BDAddons#233]
### only show gif button, or allow user to choose which chatbar buttons they want to have

I enjoy this plugin but the fact that there are now 4 buttons (gif, audio, image, video) to send media clutters the chat bar. I'd like a togglable option to show only the gif button to minimize clutter, since this is generally the most used button around discord. I think this is a decent solution because the other options are accessible via the tabs at the top of the window for selecting your media. (if you dont like gif as the only button option then maybe allow the user to choose which buttons they'd like to keep in the chat bar or something like that) Thank you!

**Comment by Dastan21** [comment]
This feature exists already.
![image](https://github.com/Dastan21/BDAddons/assets/58090137/71d30030-a407-4447-a6a8-6c6a605c0ea5)

**Comment by Megalodab** [comment]
lmao thank you im sorry i didnt check there
