### ISSUE TITLE
[FavoriteMedia]: all categories show nothing upon opening

### ISSUE THREAD

**Issue by rocketbuuny** [Dastan21/BDAddons#235]
### Discord Build

Stable

### Discord Version

Stable 256231 (96a39c5)

### Plugin Version

1.8.14

### Steps To Reproduce

1. in any chat where you have permission to type, click of gifs button
2. click on favorites
3. nothing shows up in favorites even if I have something favorited

### Describe the bug

Whenever I have the plugin enabled, I can favorite images, videos, audios, etc (what the plugin allows you to do), but when I go to look at my favorites, nothing shows up. This bug happens on all forms of media and file types (ex: .jpg/.jpeg/.png/.wav/.mp3, etc)

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/140739502/272adbc0-773c-4752-9032-5ebb33066a71)

^ I favorite it(idk if the star not being filled is related or not)

![image](https://github.com/Dastan21/BDAddons/assets/140739502/a635159a-2e8f-4182-b2be-c8fb755e59ab)

^ Nothing shows up...

**Comment by Dastan21** [comment]
Still happening?
