### ISSUE TITLE
[FavoriteMedia]: Catagories not working right

### ISSUE THREAD

**Issue by bob-carter** [Dastan21/BDAddons#236]
### Discord Build

Stable

### Discord Version

Stable 256231 (96a39c5)

### Plugin Version

v1.8.14

### Steps To Reproduce

1. Install plugin
2. Add images to favs
3. Create category in images tab
4. Drag and drop into category
5. Notice how it is still image tab, and is duplicated in category.

### Describe the bug

When I copy a image into a category, it doesn't move the image into it, but just creates a copy in the category.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/46971019/82198e2f-f021-4a50-b701-c490a6183a29)

**Comment by bob-carter** [comment]
Sorry if the images are offensive, I figured the images were at least SFW

**Comment by Dastan21** [comment]
Ensure this option is disabled
![image](https://github.com/Dastan21/BDAddons/assets/58090137/f15566f1-7b98-4c1f-817a-0b1540e31f87)

**Comment by bob-carter** [comment]
Sorry, you can close this, didn't realize that's what that setting did. Language was unclear.
I figured it hid anything not in a category, not hide anything already in a category.

**Comment by Dastan21** [comment]
Will update the description then :)
