### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by tgrafk12** [Dastan21/BDAddons#237]
### Describe the solution you'd like

I know this plugin is for BetterDiscord, but would there be a way to convert this to Vencord?
I tried to throw it in a plugins folder inside Vencord, but im new to it, and so far it runs FAR faster than BetterDiscord when it comes to responsive-ness with plugins loaded.
If there is no way to convert it, thats fine, it's just very easy to save a meme, or photo that ive already uploaded to Discord and then just click the image again to send it to another friend...

Thanks for your time :>

**Comment by Dastan21** [comment]
Hi, only BetterDiscord is supported, sorry.
