### ISSUE TITLE
[FavoriteMedia]: Uploading Gifs 

### ISSUE THREAD

**Issue by KlintGit** [Dastan21/BDAddons#238]
### Discord Build

Stable

### Discord Version

Stable 259781 (ed42aff)

### Plugin Version

1.8.14

### Steps To Reproduce

1. Go into Gif settings
2. Tick "Always upload a file" on
3. Go into a any random chat room
4. From your favorites, click on any gif

### Describe the bug

For whatever reason, setting the "Always upload a file" option for Gifs to on uploads a random gif in place of what you clicked on. I don't see any errors.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/145265642/239b1f6d-6da7-419c-8adb-042e44e955e4)
![image](https://github.com/Dastan21/BDAddons/assets/145265642/5f0622fd-5579-4863-8bd4-945a6c5e5c0f)

**Comment by Dastan21** [comment]
Fixed in v1.8.16
