### ISSUE TITLE
[FavoriteMedia]: Gifs being favorited as Images

### ISSUE THREAD

**Issue by Islands12345** [Dastan21/BDAddons#239]
### Discord Build

Stable

### Discord Version

Stable 267220 (6b16dbc)

### Plugin Version

1.8.14

### Steps To Reproduce

1. Send gif
2. Attempt to favorite it

### Describe the bug

Favoriting a gif puts it in Images and then sends it as a video. The gif never makes it to favorited gifs

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/130198020/e7695dac-cc3e-417d-a790-baf58374abdd)
![image](https://github.com/Dastan21/BDAddons/assets/130198020/57184b88-5167-405c-9eca-39b2d8fa7698)

**Comment by Dastan21** [comment]
Fixed in v1.8.15
