### ISSUE TITLE
[FavoriteMedia]: Unavailable video but the link still work

### ISSUE THREAD

**Issue by AlphaGaming7780** [Dastan21/BDAddons#240]
### Discord Build

Stable

### Discord Version

stable 267220 (6b16dbc)

### Plugin Version

1.8.15

### Steps To Reproduce

IDK, look like something happen to discord. I don't think it comes from the plugin, some video still appears.

### Describe the bug

Video are unavailable.
![image](https://github.com/Dastan21/BDAddons/assets/69048433/2a5caa15-bec9-4a8a-8caf-1cc47b667e10)

If I click on the link (https://cdn.discordapp.com/attachments/1132037909470519407/1134500923738173440/csc.mp4), I get that : 
![image](https://github.com/Dastan21/BDAddons/assets/69048433/d3c467ba-84ca-469a-9103-4aea78075bc4)

If I copy past the link in Discord: 
![image](https://github.com/Dastan21/BDAddons/assets/69048433/95e76e40-6262-4a2d-a91a-b8e2db14ba28)

**Comment by AlphaGaming7780** [comment]
Some video stills appear, but I can't play them or send them.
![image](https://github.com/Dastan21/BDAddons/assets/69048433/2299b0dd-41d7-4f7f-bf40-524b50b3e97a)
![image](https://github.com/Dastan21/BDAddons/assets/69048433/97de0846-0fff-4d26-924c-efa6c8707876)

**Comment by ItMeSarah** [comment]
Discord now enforces media and cdn links having the expiration parameters in the url. if it has no expiration parameters or has invalid/expired parameters the attachment won't work. This includes sounds, gifs, videos, images, both current and old. Expirations are 14 days from when the attachment was posted.

**Comment by DiaxManPl** [comment]
Discord fixed it in default vaorite gifs applet. Maybe I will be able to make a PR that would replicate what they did since I think it's possible to refresh links thru discord api

**Comment by Dastan21** [comment]
Added context menu option to refresh links in 1.9.0 (waiting for BD approval)

**Comment by SENPAIforME** [comment]
> Added context menu option to refresh links in 1.9.0 (waiting for BD approval)

I can't find it :(

**Comment by Dastan21** [comment]
> I can't find it :(

Right-click at the root of a media picker (not on a media card)

**Comment by SENPAIforME** [comment]
> > I can't find it :(
> 
> Right-click at the root of a media picker (not on a media card)

Cool! Thanks!

**Comment by minnieoo** [comment]
it wooorks! ty so much for this awesome update.

**Comment by AlphaGaming7780** [comment]
I'm still on 1.8.16, can't get the update.

**Comment by minnieoo** [comment]
> I'm still on 1.8.16, can't get the update.

just redownload the plugin js file. i deleted the old one and dragged and dropped it into the plugin folder. ur pics will still be there

**Comment by AlphaGaming7780** [comment]
Better Discord always says it's 1.8.16.
I try to re-download it and install it, I got the same version.
![Image.](https://github.com/Dastan21/BDAddons/assets/69048433/01ffdec9-4eb0-43cf-8525-93b72b03af01)

**Comment by AlphaGaming7780** [comment]
I got the update, thank you, it's working now.

**Comment by nathan60107** [comment]
It works. Thanks a lot. ❤️
