### ISSUE TITLE
[FavoriteMedia]: Preview images fail to display after transferring plugin settings to another computer.

### ISSUE THREAD

**Issue by nathan60107** [Dastan21/BDAddons#241]
### Discord Build

Stable

### Discord Version

Stable 268600(674960b)

### Plugin Version

1.9.7

### Steps To Reproduce

1. Save some non-gif media files on computer1.
2. Copy the entire BD plugins folder located at `C:\Users\<username>\AppData\Roaming\BetterDiscord\plugins` to computer2.
3. Upon opening Discord on computer2, notice that previews of images with URLs starting with `cdn.discordapp.com` fail to display correctly.

### Describe the bug

I'm uncertain whether this is a bug. Is there a possible solution, like manually transferring some images to computer2, that could resolve the issue?
Thank you for creating this plugin; it's incredibly helpful.

### Screenshots

![圖片](https://github.com/Dastan21/BDAddons/assets/18046878/b0179aaf-c430-4685-8479-a7abbdd576c8)

**Comment by githubguy217** [comment]
also got the same thing, also for videos too

**Comment by Dastan21** [comment]
Duplicate #240
