### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by HalfAsleepAdam** [Dastan21/BDAddons#242]
### Discord Build

Stable

### Discord Version

stable 273091 (93b3753) Host 1.0.9034 x86 (44142) Windows 10 64-bit (10.0.19045)

### Plugin Version

v1.8.16

### Steps To Reproduce

Literally just look at the thumbnail of any video saved for over 2 weeks

### Describe the bug

The entire issue is that thumbnails refuse to load on videos and images above two weeks of age. That's as clear and concise as is the issue is. The videos embed fine into discord for example sending it but the thumbnail doesn't load. Suggestion for fixing: could reload all thumbnails on startup (toggleable setting) and add a manual reload button to the thumbnails, and save each thumbnail (compressed) to save space with the files being deleted upon unfavoriting.

### Screenshots

![video tab thumnails](https://github.com/Dastan21/BDAddons/assets/88072951/72eddc71-5ea5-45fd-84b0-36b843c0974b)

**Comment by Dastan21** [comment]
Duplicate #240
