### ISSUE TITLE
[FavoriteMedia]: Save Pre-views

### ISSUE THREAD

**Issue by bob-carter** [Dastan21/BDAddons#244]
### Describe the solution you'd like

I would like to have the plugin cache a saved pre-view of images, so that when they stop refreshing the saved link it still shows what the image was. Since a lot of image pre-views seem to stop working after a week or two, and this makes the plugin as is a lot less useful, even if the links all still work. This shouldn't even be that much more work since it already saves preview height and weight if I recall. If bloat or other such things are an issue you can maybe access discords pre-existing cache of images, or make it an option to not save pre-views.

**Comment by Dastan21** [comment]
Medias previews (image, video, gif) are now getting cached in v1.10.0.
