### ISSUE TITLE
[FavoriteMedia]: Dump all images/videos/gifs option

### ISSUE THREAD

**Issue by bob-carter** [Dastan21/BDAddons#245]
### Describe the solution you'd like

I've been using this plugin for years, and more then once I've had to manually dump all my Favorite Media saved to the plugin and use notepad++ to go and delete text and post images in batches of 20 or so links, to then resave them to the plugin. 

So what I'm asking is for an option to dump or export all media links from plugin, so they can then be resaved for whenever these issues happen.

**Comment by crashthefoxbody** [comment]
I'm having a similar issue. After a week or so my images/videos just stop showing previews and sometimes some of them don't embed properly, they just embed as a file to download.

**Comment by bob-carter** [comment]
> I'm having a similar issue. After a week or so my images/videos just stop showing previews and sometimes some of them don't embed properly, they just embed as a file to download.

This is a feature request, discord changed how it handles links, and thus it isn't something that can be "fixed"

This thread is not a bug report either.
