### ISSUE TITLE
[FavoriteMedia]: Broken thumbnail images

### ISSUE THREAD

**Issue by minnieoo** [Dastan21/BDAddons#246]
### Discord Build

Stable

### Discord Version

stable 282068

### Plugin Version

v1.8.16

### Steps To Reproduce

1. Attempt to view your saved images

### Describe the bug

The thumbnails display a red X. This is an issue because I can't see what the images, and the slow solution i've been doing so far is clicking and sending them to myself, unfavoriting them, and then favoriting them again. It would be nice if there was a way to refresh them so that thumbnails can be fixed

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/137783738/3a8a656c-2fbd-4091-8a6e-b3ba9b0ed630)

**Comment by Dastan21** [comment]
Duplicate https://github.com/Dastan21/BDAddons/issues/240
