### ISSUE TITLE
[FavoriteMedia]: Refresh urls does not work in the gif section

### ISSUE THREAD

**Issue by telqr** [Dastan21/BDAddons#247]
### Discord Build

Stable

### Discord Version

Stable 285561

### Plugin Version

1.9.0

### Steps To Reproduce

1. Enable "Replace discords GIFs tab" under GIF settings in plugin settings
2. Right-click on the root, no refresh URLs button pops up only in the gif section

### Describe the bug

only happens to the gif section, but you can still refresh URLs in all the other tabs.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/129940833/6830b08b-2511-4154-8ccb-91aaf6063c58)
![image](https://github.com/Dastan21/BDAddons/assets/129940833/e9c72212-065b-4626-bb85-ea5dbd7eea7d)

**Comment by Dastan21** [comment]
Its intended, I couldn't fix GIFs cuz they're stored in a different way by Discord

**Comment by MahdeenSky** [comment]
I cant find the refresh urls button, theres none 
![Screenshot 2024-04-18 at 6 39 38 PM](https://github.com/Dastan21/BDAddons/assets/49484385/7174f533-98a8-4e9e-9c8f-0c6e3b42dd44)
