### ISSUE TITLE
Suggestion to keep displaying the favorite media panel after uploading the media

### ISSUE THREAD

**Issue by Zagreus12** [Dastan21/BDAddons#25]
If I am trying to upload multiple images or videos or whatever its really annoying to open it and have to scroll all the way down everytime. If an option/setting to keep the panel open was added that would be greatly appreciated.

**Comment by Dastan21** [comment]
This feature already exists : hold shift while posting medias 😉

**Comment by gamerinbg123** [comment]
> 

Thank you
