### ISSUE TITLE
[FavoriteMedia]: Most media previews displaying error

### ISSUE THREAD

**Issue by Fallen-Feces** [Dastan21/BDAddons#250]
### Discord Build

Stable

### Discord Version

Stable 290453

### Plugin Version

1.9.0

### Steps To Reproduce

1. Click media tabs
2. Confusion

### Describe the bug

Clicking any media tab such as gifs, images, or videos leads to most if not all previews displaying that error image with the blue background and red paper with an x.

The audio tab works fine but that's not really surprising. I don't really remember when this issue started. I guess at first I just assumed some connection error and it'd fix itself eventually but it's only been getting worse to the point that now entire pages are nothing but errors and I have to post a link to see what it even is.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/44452380/875c3454-b846-41ba-a813-c90c97fecdab)
![image](https://github.com/Dastan21/BDAddons/assets/44452380/074ccb97-800b-42c3-bedc-f7a3eef3c0d5)
![image](https://github.com/Dastan21/BDAddons/assets/44452380/80f93161-c653-45a0-9843-4a0367c7d295)

**Comment by Fallen-Feces** [comment]
Ok I didn't realize this before but actually clicking these things uploads a 36 byte file with the respective name. Right clicking and pressing any of "Copy media/message link" or Message does work and sends/copies a functional image link, but just clicking the image or hitting upload gives the busted 36 byte file (I enabled the option to upload files directly instead of a link by default). It downloads _something_ when I click download but windows defender instantly nabs it and calls it a trojan.

**Comment by Halokiller990** [comment]
This happens when the media link expires. Discord made some changes recently that makes discord embed links expire after a certain amount of time. You can right click on a blank space in the media tab to refresh the URLs. Although it doesn't work for gifs. It also doesn't work when you have a large amount of media favorited because you get rate limited. (I already created an issue about this)

**Comment by Fallen-Feces** [comment]
Yeah, unfortunately refreshing the urls doesn't seem to be doing anything. I assume I'm being rate limited then since 20+ pages are quite a lot.

**Comment by misterpyrrhuloxia** [comment]
> Yeah, unfortunately refreshing the urls doesn't seem to be doing anything. I assume I'm being rate limited then since 20+ pages are quite a lot.

@Fallen-Feces, I wonder if the rate-limiting could be worked around by the plugin only ever loading the current page of favorited items that we're on and only load other pages upon navigating to them? If that would work, it'd be nice to have a plugin setting that would let us choose if we want to pre-load more than one page and, if so, how many pages ahead and behind to pre-load.

**Comment by Dastan21** [comment]
Medias previews (image, video, gif) are now getting cached in v1.10.0.
