### ISSUE TITLE
[FavoriteMedia]: Tabs dont show

### ISSUE THREAD

**Issue by AliceTheFurry18** [Dastan21/BDAddons#251]
### Discord Build

Stable

### Discord Version

latest

### Plugin Version

latest

### Steps To Reproduce

just use it on discord

### Describe the bug

The tabs for favorite media is not appearing

**Comment by minnieoo** [comment]
Same issue started for me just now.
![image](https://github.com/Dastan21/BDAddons/assets/137783738/76d5943f-c4d7-4e4a-aa42-e2fab58a2196)

**Comment by Komrade-Yanouchka** [comment]
![image_2024-05-14_163147309](https://github.com/Dastan21/BDAddons/assets/68874488/a2094cc4-aca4-4143-82ab-e41dd08c646a)
yes and if you open it with the shortcut it's just blank

**Comment by githubguy217** [comment]
i have same issue too

**Comment by Dastan21** [comment]
Fixed in v1.9.1, waiting for BD approval.
