### ISSUE TITLE
[FavoriteMedia]: Return functionality to middle-click an image to open media in external application

### ISSUE THREAD

**Issue by Tsaukpaetra** [Dastan21/BDAddons#253]
### Describe the solution you'd like

I often find myself middle-clicking an image to instantly call the "Open in Browser" function, but it seems this plugin overrides the behavior entirely and handles only Click (I think as a limitation of the clickableWrapper?)

Anyways, around line 2663 when it creates the new click handler, I tossed this bit of BS code to try and workaround it for the time being...

```
            if (e && (e.which == 2 || e.button == 4 || e.ctrlKey )) {
              window.open(data.url.replace('media.discordapp.net', 'cdn.discordapp.com').replace(/(\?|&)width=([\d]*)&height=([\d]*)/, ''))
              return;
            }
```

That allows me to ctrl-click and have effectively the same functionality.

**Comment by Dastan21** [comment]
Fixed in v1.10.0.
