### ISSUE TITLE
[FavoriteMedia]: Sending an image from the panel causes a weird panel to appear

### ISSUE THREAD

**Issue by minnieoo** [Dastan21/BDAddons#254]
### Discord Build

Stable

### Discord Version

Discord Info stable 299298 (bb93e73)

### Plugin Version

v1.9.1

### Steps To Reproduce

1. Send image from favoritedmedia panel

### Describe the bug

This shows up directly after sending an image with the panel. It goes away when I go into my settings and come back or right click anywhere. I also got this console error despite the image sending normally, unsure if it is related, especially since the console error doesn't always happen. I disabled all other plugins to make sure it was FavoriteMedia causing this.
![image](https://github.com/Dastan21/BDAddons/assets/137783738/fa254e62-ecc2-4e34-967e-14cc79ecca3a)
![image](https://github.com/Dastan21/BDAddons/assets/137783738/7a115c12-8259-4d03-867b-a4af3c384a88)
![Adobe_Premiere_Pro_sTbowplmgI](https://github.com/Dastan21/BDAddons/assets/137783738/f0369288-ee24-42e2-a549-f261b82bac60)

**Comment by Dastan21** [comment]
Could you try without themes

**Comment by minnieoo** [comment]
good thinking, i think that was the issue! i was using Fluent Discordv1.10.6 by TakosThings. i can't replicate this when i turn the theme off.
