### ISSUE TITLE
[FavoriteMedia]: no button to save image

### ISSUE THREAD

**Issue by Komrade-Yanouchka** [Dastan21/BDAddons#255]
### Discord Build

Stable

### Discord Version

stable 301920 (198d4c4)

### Plugin Version

1.9.1

### Steps To Reproduce

1. hover mouse on image 2. no star button appears 

### Describe the bug

normally a star shaped button would appear on the top left when hovering the mouse on an image but it doesn't at the moment.

### Screenshots

works on video
![image_2024-06-16_235807516](https://github.com/Dastan21/BDAddons/assets/68874488/be3de742-2256-43d4-a62c-e9979df78490)

not on image
![image_2024-06-16_235926197](https://github.com/Dastan21/BDAddons/assets/68874488/60f358d4-e389-4efd-9a24-ac00feeb3ade)

**Comment by TheConfusedlol** [comment]
Same here

**Comment by Dastan21** [comment]
Fixed in v1.10.0.
