### ISSUE TITLE
[FavoriteMedia]: Crash on Category Modal

### ISSUE THREAD

**Issue by Piquixel** [Dastan21/BDAddons#256]
### Discord Build

Stable

### Discord Version

Stable 302556 (366c746)

### Plugin Version

1.9.1

### Steps To Reproduce

1. Create or Edit a Category
2. Discord crashes

### Describe the bug

When trying to create or edit a category, Discord crashes trying to show the category modal.

**Comment by Dastan21** [comment]
Fixed in v1.10.0.
