### ISSUE TITLE
[FavoriteMedia]: An error was encountered while trying to load this plugin.

### ISSUE THREAD

**Issue by AlphaGaming7780** [Dastan21/BDAddons#258]
### Discord Build

Stable

### Discord Version

Stable 303105 (1897d8a)

### Plugin Version

1.9.1

### Steps To Reproduce

Have the plugin installed
And try to load it

### Describe the bug

BetterDiscord can't load the plugin : An error was encountered while trying to load this plugin.

### Screenshots

![image](https://github.com/Dastan21/BDAddons/assets/69048433/0d61afe5-4ef4-41eb-89ff-0fbd72a94ac6)

**Comment by Dastan21** [comment]
Duplicate #257
