### ISSUE TITLE
[FavoriteMedia]: Make FavoriteMedia refresh urls automatically [feature request]

### ISSUE THREAD

**Issue by minnieoo** [Dastan21/BDAddons#259]
### Describe the solution you'd like

I always want the URLs to be refreshed so I can see my favorited images. A convenient feature would be to have the URLs refresh automatically, rather than having to do it manually. Perhaps include an option for users to set the URLs to refresh on a schedule, ranging from every 30 minutes to every 24 hours, with various intervals in between.

Something like 'set urls to refresh every: 30 mins, 1 hour, 6 hours, 12 hours, 24 hours'

**Comment by Dastan21** [comment]
The next update will deprecate the temporary "refreshed links"

**Comment by minnieoo** [comment]
does that mean it will no longer be possible to refresh URLs at all?

**Comment by Dastan21** [comment]
Medias previews (image, video, gif) are now getting cached in v1.10.0.
