### ISSUE TITLE
[HideEmbedLink]: Seems HideEmbedLink doesn't work

### ISSUE THREAD

**Issue by Joolian1** [Dastan21/BDAddons#260]
### Discord Build

Stable

### Discord Version

Latest version ( sorry can't check using phone )

### Plugin Version

2.1.4

### Steps To Reproduce

I used to use this plugin long time ago like a year or so, then it stopped got developed after the huge updates but now i saw it updated a week or so, i tried to download it then using it like normal way it didn't hide the link for twitter or anything..

### Describe the bug

I used to use this plugin long time ago like a year or so, then it stopped got developed after the huge updates but now i saw it updated a week or so, i tried to download it then using it like normal way it didn't hide the link for twitter or anything..

Is it updated or did i do something wrong?

**Comment by Dastan21** [comment]
Fixed in v2.1.5
