### ISSUE TITLE
[FavoriteMedia]: Media Previews are not showing, but sending works, and local DB results in an error.

### ISSUE THREAD

**Issue by MahdeenSky** [Dastan21/BDAddons#261]
### Discord Build

Stable

### Discord Version

latest

### Plugin Version

1.10.0

### Steps To Reproduce

Click image/video tabs.

Click local DB.

### Describe the bug

1. Images, and Videos tab look something like this.
<img width="537" alt="Screenshot 2024-07-14 at 6 19 41 PM" src="https://github.com/user-attachments/assets/a1ee9e6f-24d7-4d89-8add-a18739e20bb7">

2. When i attempt to send one of these, it does end up sending the actual media but the preview does not update, so it still shows up as the "X on file" in the tab.

3. Also clicking local DB, results in an error.
<img width="479" alt="Screenshot 2024-07-14 at 6 23 23 PM" src="https://github.com/user-attachments/assets/9babd71c-9b70-4cef-a8c8-8a02689def1c">

- On inspecting the console logs, this shows up.
<img width="713" alt="Screenshot 2024-07-14 at 6 25 49 PM" src="https://github.com/user-attachments/assets/f949cf5b-31d4-4ca7-9b79-368d4337009c">

**Comment by Dastan21** [comment]
My bad, fixed now (same version).
