### ISSUE TITLE
[FavoriteMedia]: Random Media Previews in image/video tab even after caching medias locally, appear to be broken

### ISSUE THREAD

**Issue by MahdeenSky** [Dastan21/BDAddons#262]
### Discord Build

Stable

### Discord Version

latest

### Plugin Version

1.10.0

### Steps To Reproduce
Cache locally the media and then
Have multiple media in image/videos tab, scroll it to see random medias just having broken previews.

### Describe the bug

1. There will be random media's which have broken previews, but can actually be sent/have previews.

https://github.com/user-attachments/assets/c32221ee-8fc7-4f1e-99b8-12211c347ea6

2. Upon checking console, it turns out that the preview images were 404'd in other words, NOT FOUND, which means they were formerly valid preview images, and might've expired.

3. I'd reckon an easy fix would be to regenerate the previews using the discord api if possible, or the other hacky way which involves uploading the video, sending it in a channel, and then staring it, putting it back to it's original place in your media folder by taking the thumbnail url for that just sent media.

**Comment by Dastan21** [comment]
If you clicked on "Cache all medias" in the "Local database" panel, it should work fine. Maybe try again the button. Otherwise share some of the medias that won't cache thanks.

**Comment by MahdeenSky** [comment]
> If you clicked on "Cache all medias" in the "Local database" panel, it should work fine. Maybe try again the button. Otherwise share some of the medias that won't cache thanks.

Oh I forgot to add that this happened after I cached locally. I'll try it a second time and tell you how it goes.

**Comment by SALM0NSalaD** [comment]
I have the exact same problem. I cached everything I could. Videos and pictures have correct previews, but most of the gifs don't display them.
Examples:
https://tenor.com/view/cat-dance-cat-blob-cat-cat-rave-gif-26380138
https://tenor.com/view/1984-gif-3810568190062003698

**Comment by Dastan21** [comment]
> I have the exact same problem. I cached everything I could. Videos and pictures have correct previews, but most of the gifs don't display them. There seems to be a problem with all tenor gifs. If there is a need to provide additional information, please write to me. Examples: https://tenor.com/view/cat-dance-cat-blob-cat-cat-rave-gif-26380138 https://tenor.com/view/1984-gif-3810568190062003698

Fixed for GIFs (same version).

**Comment by MahdeenSky** [comment]
Btw can you commit this to the master branch? because that one gets updated to BD, so it auto updates the plugin, whenever its updated, otherwise we'd have to check this repo once in a while.

**Comment by Dastan21** [comment]
> Btw can you commit this to the master branch? because that one gets updated to BD, so it auto updates the plugin, whenever its updated, otherwise we'd have to check this repo once in a while.

BD verification takes time, that's why I can push quick fixes/changes without bumping version. Their verification system loads the latest commit.

**Comment by Rexxxyxyxy** [comment]
Hey i updated through here and all my saved media dissapeared what happened?

**Comment by Dastan21** [comment]
Can you provide some of the broken urls thanks

**Comment by Rexxxyxyxy** [comment]
> Can you provide some of the broken urls thanks

https://cdn.discordapp.com/attachments/1247433337631674410/1247435107820900423/0603.mp4?ex=66751bf9&is=6673ca79&hm=0e113aefc398b6833163c8eec2f5db0cfd2ff5c3bad6944589fa313f95af5442&

**Comment by Rexxxyxyxy** [comment]
> > Can you provide some of the broken urls thanks
> 
> https://cdn.discordapp.com/attachments/1247433337631674410/1247435107820900423/0603.mp4?ex=66751bf9&is=6673ca79&hm=0e113aefc398b6833163c8eec2f5db0cfd2ff5c3bad6944589fa313f95af5442&

https://cdn.discordapp.com/attachments/1241525846775300146/1247048926595383398/BonniejumpscareDIEe.mov?ex=667505d1&is=6673b451&hm=32ebbe829e0faaad2bb0f3c11d7b48831524fa63740caf5d3b8123c875c0a5db&
https://cdn.discordapp.com/attachments/1241525846775300146/1246176605194293248/VideoStar.mov?ex=66752527&is=6673d3a7&hm=9cb01fbaa73423e5b3803fb0062cbdcd5fa56092a836401d624ebf7f59a10c00&

**Comment by Rexxxyxyxy** [comment]
![image](https://github.com/user-attachments/assets/e9b7191d-8ae8-4392-b92b-75e6a4ad39c0)
images stopped working tonight too

**Comment by Dastan21** [comment]
> Otherwise share some of the medias that won't cache thanks.

@MahdeenSky no longer an issue?

**Comment by MahdeenSky** [comment]
> > Otherwise share some of the medias that won't cache thanks.
> 
> @MahdeenSky no longer an issue?

Yeah, seems like caching it multiple times did the trick, although there are some that dont preview, but at the same time those dont work even when sending so no issue with that.
