### ISSUE TITLE
[FavoriteMedia]: The add to favorites button is missing on GIFs

### ISSUE THREAD

**Issue by SALM0NSalaD** [Dastan21/BDAddons#263]
### Discord Build

Stable

### Discord Version

stable 309513 (4058dd9)

### Plugin Version

1.10.0

### Steps To Reproduce

1. Div "imageAccessory_d4597d" does not contain "gifFavoriteButton_" before hovering. It has "gifTag_" instead
2. The div "imageAccessory_d4597d" is changed when the status is "focus" on the GIF. It adds "gifFavoriteButton_" replacing "gifTag_", but it doesn't display the button on top of the GIF. 

### Describe the bug

 The add to favorites button is missing on GIFs. This problem is not observed with other media files other than GIFs.

**Comment by Dastan21** [comment]
I don't understand your steps. Does the issue appear without doing anything?

**Comment by SALM0NSalaD** [comment]
Yes. I don't have the button displayed when hovering over the Gif. If I disable the plugin, the button appears in the form again

**Comment by Dastan21** [comment]
Ok found the issue, it's because you have the setting "Replace Discord GIFs tab" disabled.

**Comment by Dastan21** [comment]
Fixed (same version).
