### ISSUE TITLE
[FavoriteMedia]: the new update just constantly crashes when you try to review cache i rather just go back to the old way when you manually 

### ISSUE THREAD

**Issue by Rexxxyxyxy** [Dastan21/BDAddons#265]
### Discord Build

Stable

### Discord Version

latest

### Plugin Version

1.10.0

### Steps To Reproduce

download plugin use it refresh cache then infinite crash

### Describe the bug

quite literally all the previews mess up and i cant even go to cache without it crashing i know its this plugin causing it because it only crashes once i turn it on and its quite annoying

**Comment by Dastan21** [comment]
any error log?

**Comment by Rexxxyxyxy** [comment]
Uploading Desktop 2024.07.19 - 12.32.12.26.mp4…

**Comment by Rexxxyxyxy** [comment]
i dont think so

**Comment by Dastan21** [comment]
> Uploading Desktop 2024.07.19 - 12.32.12.26.mp4…

fail

**Comment by Rexxxyxyxy** [comment]
https://github.com/user-attachments/assets/e5d6d338-ea21-42cd-b97a-9c601d2bc514

**Comment by Dastan21** [comment]
1. open the console
2. enable plugin
3. share logs

also how many medias do you have? like over 2k?

**Comment by Rexxxyxyxy** [comment]
Not even like 200 max and how exactly do i open up the console?

**Comment by Dastan21** [comment]
ctrl + shift + i

**Comment by Rexxxyxyxy** [comment]
![image](https://github.com/user-attachments/assets/5fd09d7e-b889-4f76-93df-0a0448ebc09b)
![image](https://github.com/user-attachments/assets/d352da65-aae9-44c4-bf3b-46edf8cade56)
![image](https://github.com/user-attachments/assets/b7ed17eb-c414-4e95-8f64-afaa92447b40)
![image](https://github.com/user-attachments/assets/c3ecff33-7bfa-44e2-a402-36bb6e5dfa69)

**Comment by Dastan21** [comment]
when you enable the plugin

**Comment by Rexxxyxyxy** [comment]
![image](https://github.com/user-attachments/assets/98accd99-e5a3-455d-8b27-fb3dc260bcd5)

last thing it said before it crashed

**Comment by Dastan21** [comment]
pls share your config.json so I can test locally

**Comment by Rexxxyxyxy** [comment]
[FavoriteMedia.config.json](https://github.com/user-attachments/files/16316643/FavoriteMedia.config.json)

**Comment by Dastan21** [comment]
![image](https://github.com/user-attachments/assets/b4e1426b-166b-4cd6-8ffa-92e652d152e8)

Worked fine for me.
You can edit the config.json and set `allowCaching` as false to stop the crash, then go to the database panel and clear it.
You could try enabling the setting again after.

**Comment by Rexxxyxyxy** [comment]
hmm lemme try

**Comment by Rexxxyxyxy** [comment]
it crashes without config in?

**Comment by Dastan21** [comment]
it would because the setting `allowCaching` - which loads previews from the database and proceeds to crash - is enabled by default

**Comment by Rexxxyxyxy** [comment]
![image](https://github.com/user-attachments/assets/08a8de99-c089-4404-9d83-632c1233da84)

**Comment by Rexxxyxyxy** [comment]
time to try

**Comment by Rexxxyxyxy** [comment]
alright so when i try to turn it back on it crashes again which sucks anyway you can just gimmie like a hotfix so i manually refresh it or smth

**Comment by Dastan21** [comment]
check console on the first crash pls

**Comment by Rexxxyxyxy** [comment]
![image](https://github.com/user-attachments/assets/beed9a31-5aa4-4271-bec1-f89262276608)

**Comment by Dastan21** [comment]
it may be related to this https://github.com/Dastan21/BDAddons/issues/264#issuecomment-2235162861

**Comment by Rexxxyxyxy** [comment]
crashes right after that last one

**Comment by Rexxxyxyxy** [comment]
well i would greatly appreciate like.. a work around hopefully one thats not gonna take tooo long you know last time was a while

**Comment by Dastan21** [comment]
Fixed in 1.10.1, now the medias urls are loaded in cache only when needed, no longer on startup/plugin enabling.
