### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by DeCat4** [Dastan21/BDAddons#266]
### Discord Build

Stable

### Discord Version

Stable 313344 (a8eb55c)

### Plugin Version

1.10.1

### Steps To Reproduce

Unknown, i had these medias favorited for like a week or two now their preview is like this

### Describe the bug

Thumbnail previews for some media just stop working after a bit, deleting the cache and re caching doesn't help, sending it still works though. Re-favoriting does fix the issue but this can probably affect hundreds of images, i favorited everything within the same day if that helps to know

I have a folder with 70 images in it, half of page 1's previews no longer work, the rest are fine, all of the images within this folder are posted by me in a channel within a server i own, i favorited those on the same day

### Screenshots

![image](https://github.com/user-attachments/assets/3f0ee226-7830-4849-a04f-902e7400add7)

**Comment by Taupe** [comment]
Happens to me as well. There was a way to refresh medias and get the thumbnails showing but it was removed in the latest update

**Comment by Taupe** [comment]
Nevermind, I found the solution.

![image](https://github.com/user-attachments/assets/b8b0f5be-e62f-4b62-92e0-5063fa45b429)
![image](https://github.com/user-attachments/assets/08a9fcfe-d571-42cf-8a9a-b6cddf6f022b)

You have to go to the local database, then select "Cache all medias"

**Comment by DeCat4** [comment]
that's what i did but it didn't work, but today all of the previews are working again so i guess maybe it fixes it on restarts

**Comment by Taupe** [comment]
Well, i guess it's a temporary workaround since i can't find any other way, we will have to wait on Dastan to potentially give us an answer and maybe a fix
