### ISSUE TITLE
[FavoriteMedia]: Local Database Cache All Media doesn't work.

### ISSUE THREAD

**Issue by SoCalledFunnyman** [Dastan21/BDAddons#268]
### Discord Build

Stable

### Discord Version

stable 315432 (4e1f4fc)

### Plugin Version

1.10.1

### Steps To Reproduce

1 - Click "Local Database"
2 - Click "Cache All Media"

### Describe the bug

It just straight up doesn't work.

I've left it running overnight multiple times, and it hasn't done anything at all. 
I've tried restarting Discord and doing it multiple times, and it hasn't done anything at all. 
The "Cache All Media" thing permanently remains as the spinning blocks, and all media previews remain as the default X that Discord uses or the "missing image" placeholder (the one that looks like a sheet of paper with a diagonal slash through the bottom right of it). See attached screenshots for what I mean.

Maybe this is only a me thing. Maybe I'm just doing something wrong. But I followed the instructions I was given to the best of my knowledge and ability, and it didn't work.

Honestly I'd prefer if the Refresh URLs thing came back, but from what I read in the other bug reports that seemed related to this, that was apparently something that was just a temporary measure that stopped working as Discord updated.

### Screenshots

![image](https://github.com/user-attachments/assets/8662bfb0-3406-4725-853c-fe47898775c8)
![image](https://github.com/user-attachments/assets/2da0c0dd-e81d-4118-bff5-3470f9141f95)

**Comment by Rexxxyxyxy** [comment]
I have been waiting to see this fixed but it is so annoying and i honestly would rather go back too because this i cant even see what im clicking on and its like Russian roulette  fix pls

**Comment by Rexxxyxyxy** [comment]
bro i think he abandoned this

**Comment by Dastan21** [comment]
@SoCalledFunnyman Can you share your config.json so that I can test out thx

**Comment by Rexxxyxyxy** [comment]
mines does the same do you want me to share mine

**Comment by Dastan21** [comment]
Please do

**Comment by Rexxxyxyxy** [comment]
[FavoriteMedia.config.json](https://github.com/user-attachments/files/16740489/FavoriteMedia.config.json)

**Comment by Dastan21** [comment]
@Rexxxyxyxy Caching worked fine on my computer, it has cached a total of 943. A few previews won't load but it's because they're completely dead. And while caching, my RAM and CPU% were normal. Idk...

**Comment by Rexxxyxyxy** [comment]
![image](https://github.com/user-attachments/assets/9df3dec5-5aeb-4134-a64f-d3aa38183d40)

**Comment by Rexxxyxyxy** [comment]
still wont for me what do i delete and readd or what?

**Comment by Dastan21** [comment]
![image](https://github.com/user-attachments/assets/8e6021e4-7dfb-45c9-9b60-95428c4a735b)

If the caching is working, it should display a progress.

**Comment by Rexxxyxyxy** [comment]
mines would just crash tbh

**Comment by Rexxxyxyxy** [comment]
when i try to look at cache it would just instant crash

**Comment by Dastan21** [comment]
Nothing shows up in the console when it crashes ?

**Comment by SoCalledFunnyman** [comment]
> @SoCalledFunnyman Can you share your config.json so that I can test out thx

Sorry for such a late response. Here you go. At least this SHOULD be it, I think.
[FavoriteMedia.config.json](https://github.com/user-attachments/files/16920114/FavoriteMedia.config.json)
Tested again today. Same thing. No progress tracker at all. Just the endlessly spinning squares.

**Comment by Dastan21** [comment]
really weird...
![image](https://github.com/user-attachments/assets/f1ac8fb0-f2de-492f-aa6b-4702f408e275)

**Comment by Dastan21** [comment]
Wait, maybe I did not understand correctly, you have never seen this button?
![image](https://github.com/user-attachments/assets/a4968bda-40aa-42df-90ae-ab55a0120ef0)

With no error in the console?

**Comment by SoCalledFunnyman** [comment]
> Wait, maybe I did not understand correctly, you have never seen this button? 
> With no error in the console?

I'm not exactly sure what you mean by that? That's the menu I go into, and it looks completely the same in that image as it does when I use it. I press the Cache All Medias button, and as previously stated, nothing ever happens.

As for the console, admittedly I haven't checked it (or at least I don't think I have anyways) since I'm not sure how to do so. If you let me know how to do that, I'll put down whatever gets shown in it here. But I've never had any crashes or anything, just the caching never seems to start after I press the button.

**Comment by Dastan21** [comment]
Ctrl+shift+i

**Comment by SoCalledFunnyman** [comment]
> Ctrl+shift+i

Alright, just did that, here's what I got after hitting the "Cache All Medias" button.
![image](https://github.com/user-attachments/assets/35410670-734b-44e3-8e53-68df3206304b)
Basically, just a whole lot of this. Also got this as well.
![image](https://github.com/user-attachments/assets/92bd27c6-5266-4acb-9231-c630cac51f0d)

**Comment by Dastan21** [comment]
[FavoriteMedia.plugin.js.zip](https://github.com/user-attachments/files/16959821/FavoriteMedia.plugin.js.zip)
@SoCalledFunnyman try with this version, and show the console logs too, because it might show why every red request fails

**Comment by Rex753** [comment]
my version just loads infinite no cache all medias and just flops can we please return to the old version 
![image](https://github.com/user-attachments/assets/19945d7c-185c-4ddb-baa2-b80a1ce9b085)
and then crashes with nothing else

**Comment by Dastan21** [comment]
@Rex753 @Rexxxyxyxy 
[FavoriteMedia.plugin.js.old.zip](https://github.com/user-attachments/files/16962740/FavoriteMedia.plugin.js.old.zip)

**Comment by Rex753** [comment]
this is js not python can i still install it?

**Comment by Dastan21** [comment]
oops forgot to rename it, rename to `FavoriteMedia.plugin.js`

**Comment by Rex753** [comment]
sick now it works dubbz

**Comment by SoCalledFunnyman** [comment]
> [FavoriteMedia.plugin.js.zip](https://github.com/user-attachments/files/16959821/FavoriteMedia.plugin.js.zip) @SoCalledFunnyman try with this version, and show the console logs too, because it might show why every red request fails

This one was mostly the same as the last one, a ton of Bad Requests intermittently broken by "Could not load media". It seemed to actually work after a bit this time though. So whatever you changed, apparently that made it work.
