### ISSUE TITLE
[FavoriteMedia]: 

### ISSUE THREAD

**Issue by NotSoHealthy** [Dastan21/BDAddons#273]
### Discord Build

Stable

### Discord Version

Stable 339221 (3687267)

### Plugin Version

1.10.3

### Steps To Reproduce

Right clicking an audio embed crashed discord

### Describe the bug

Right clicking an audio embed crashed discord

### Screenshots

![image](https://github.com/user-attachments/assets/d4ac6a82-bf6d-44ce-9c96-d876158fd67d)
Right clicking the link or the embed itself crashed discord

**Comment by Dastan21** [comment]
Fixed in v1.10.4.
