### ISSUE TITLE
PLEASE [FavoriteMedia]: So you gave me the old version since for some reason my pc wont refresh my media without it so i was wondering if you can fix the issue with the old version you gave me too?

### ISSUE THREAD

**Issue by Hackertester172** [Dastan21/BDAddons#277]
### Describe the solution you'd like

please fix it i love this plugin but my pc cant use the new one without crashing as you remember

**Comment by Hackertester172** [comment]
https://github.com/user-attachments/assets/32acad00-949e-4bdd-861e-bf3592f3f224

**Comment by Hackertester172** [comment]
and the old versions refresh stuff was way more useful to me

**Comment by WlSDXM** [comment]
sidenote: still having issues with crashing on v.1.10.4.  even with ZeresPluginLibrary toggled on/off - still crashes.

you closed #274 so i could not add more input.

i really like this plugin - hope it gets worked out soon. ty

**Comment by Hackertester172** [comment]
mines is just crashing after a bit so either way im fucked lmfao
