### ISSUE TITLE
[FavoriteMedia]: please fix it i love this plugin but my pc cant use the new one without crashing as you remember so i cant even use it

### ISSUE THREAD

**Issue by Hackertester172** [Dastan21/BDAddons#279]
### Discord Build

Stable

### Discord Version

latest

### Plugin Version

10.4

### Steps To Reproduce

just try and refresh

### Describe the bug

crashes instantly pls fix old version for people like us too

### Screenshots

https://github.com/user-attachments/assets/ab5bbdb2-ae5c-49b7-94c3-e460de77d657

**Comment by LilyBageL** [comment]
Yeah that's what happened to me too in my opened issue, nothing in the console either

**Comment by LichLord91** [comment]
broken here too

**Comment by Hackertester172** [comment]
i dont think bros gonna fix it 😭 
leaving us in the dust probs

**Comment by Dastan21** [comment]
Fixed in v1.11.1
