### ISSUE TITLE
[FavoriteMedia]: Favorited Images/Videos/Sounds don't display, despite having said media favorited

### ISSUE THREAD

**Issue by KingJigglypuff** [Dastan21/BDAddons#280]
### Discord Build

Stable

### Discord Version

stable 343474 (129221b)

### Plugin Version

1.10.5

### Steps To Reproduce

1.) Launch BetterDiscord with plugin enabled.
2.) When entering a message, click either the Image, Video, or Sound buttons.
3.) Nothing happens.

### Describe the bug

I have gifs, images, videos, and sounds all favorited, but only the gif functionality works. Attempting to access the images, videos, or sounds results in nothing happening.

**Comment by andreyka909** [comment]
Same issue, after downloading new version yesterday, it was working, on next discord launch it stopped showing any tabs outside of gif (its still the plugin version of gif section).

**Comment by Dastan21** [comment]
Fixed in v1.11.1
