### ISSUE TITLE
[FavoriteMedia]: Crash when I do... something?

### ISSUE THREAD

**Issue by Fallen-Feces** [Dastan21/BDAddons#283]
### Discord Build

Stable

### Discord Version

Stable 353815 (a932d4a)

### Plugin Version

1.12.0

### Steps To Reproduce

1. Pray you don't crash.
2. God doesn't answer.

### Describe the bug

I just entered a certain server and it crashed. Idk what really happened here. The server is consistently causing me to crash but idk why.

### Screenshots

![image](https://github.com/user-attachments/assets/7f658eff-c0ae-4eeb-aa71-5e7fbd29a5b5)

**Comment by Komrade-Yanouchka** [comment]
i have it crash when i click a media category.

**Comment by Dastan21** [comment]
Should be fixed in v1.20.1.
