### ISSUE TITLE
FavoriteMedia compatible

### ISSUE THREAD

**Issue by C44RL** [Dastan21/BDAddons#29]
can you make FavoriteMedia compatible with Discord Dark By SyndiShanX ? there are no icons with theme enabled
![Discord_FF6n91TD9h](https://user-images.githubusercontent.com/53061175/139953081-69117481-17a5-4243-8ee6-ebe363c0254f.png)

**Comment by Dastan21** [comment]
It is not to plugins devs to fix themes issues, please contact the theme dev instead.
![image](https://user-images.githubusercontent.com/58090137/139953391-7c8a623d-4483-4e22-8952-13474c68b7c6.png)

**Comment by C44RL** [comment]
okay, sry
