### ISSUE TITLE
Suggestions for FavoriteMedia plugin!

### ISSUE THREAD

**Issue by miles352** [Dastan21/BDAddons#3]
Hey, I think your plugin is really cool and I have a few suggestions on how it could be even cooler.
1. You could add an option to download the media to your computer so that if the original is deleted you can still use it.
2.  Not sure if this is intended or a bug, but if you make a category and put something in it, it is still outside the category as well.
3. Dragging things into the category could be cool, but not really necessary lol.

Again, love the plugin, keep up the great work!

**Comment by Dastan21** [comment]
Hi, I might add like your first suggestion and might look into it :) About the 2nd one, there is an option in settings to "hide" medias or not if they're in a category. And the last one I've already tried some time ago but didn't end up with anything good. I will try again when I have time :) Thx for using my plugin and your suggestions <3

**Comment by Dastan21** [comment]
Hey, in the latest version you can now :
1. download medias on your computer (added on the context menus)
3. drag unsorted medias to a category

I think the 1. is not what you expected but I'm not planning to add this feature anyway.
