### ISSUE TITLE
Request for favorite limit to be increased 

### ISSUE THREAD

**Issue by Datnyess** [Dastan21/BDAddons#31]
I may or may not be a hoarder for files but I would like to either have a choice in how much I can save at a time or an increased limit in general. thanks man

**Comment by Dastan21** [comment]
As an alternative you can create a temp folder in which you put the files you want to download, then you download the folder.

**Comment by Datnyess** [comment]
How would I go about finding where all the favorited files are saved?

**Comment by Dastan21** [comment]
Downloaded ones or as links ?

**Comment by Dastan21** [comment]
You can look into `FavoriteMedia.config.json` for raw data.
