### ISSUE TITLE
This plugin affects the margin of emojis, stickers, etc.

### ISSUE THREAD

**Issue by MatiasEsf** [Dastan21/BDAddons#32]
Hello.!
adding this plugin hides some emojis, the same happens with stickers, gifs and other discord elements. Is it possible to fix it? I really like this plugin

![fix_pls](https://user-images.githubusercontent.com/49958478/141330068-bca7aaf4-346c-40df-9ba0-9964fb50e38f.PNG)

**Comment by Dastan21** [comment]
Duplicate of #16.
