### ISSUE TITLE
Every time i open it discord crashes

### ISSUE THREAD

**Issue by TxRichardxT** [Dastan21/BDAddons#33]
Hello every time i try to open FavoriteMedia it it just crashes, i tryied by installing it again or better discord too and nothing semes to help. i dont know what more to do you think you could help me?
![dont work](https://user-images.githubusercontent.com/94150125/141390107-6b732480-17b7-48e2-a9d4-e71b1c00b825.PNG)

**Comment by TheDoggoRex** [comment]
I'm having a similar issue, my discord opens but if I try to open any of the emotes, gifs, stickers, images, or videos menu's it crashes.

**Comment by KryPixeL** [comment]
Same here. Discord opens but using the favourites menu crashes discord.

**Comment by TxRichardxT** [comment]
Then we will need to wait so they can fix it

**Comment by XM9G** [comment]
The same issue for me, whenever I open any of them it crashes.

**Comment by XM9G** [comment]
I don't think this issue is to do with this plugin, when I disable it and open the emojis it crashes.

**Comment by Dastan21** [comment]
Fixed in 31a1143 👍
