### ISSUE TITLE
FavoriteMedia still crashing

### ISSUE THREAD

**Issue by huangdangwibu** [Dastan21/BDAddons#34]
still crashing after the third reinstall: https://gyazo.com/7fde8b14695dbc533fe59e18535cac18

**Comment by Dastan21** [comment]
Are you on Stable, PTB or Canary ? I just tested on Canary and it crashes

**Comment by Dastan21** [comment]
Seems to be caused by Emoji Menu, cannot do much, just disable it (and reload) until it is fixed by BD
