### ISSUE TITLE
plugin has recently stopped working entirely

### ISSUE THREAD

**Issue by Schleeem** [Dastan21/BDAddons#39]
as of the 12/01/21 update, video, image, and audio appear completely empty and have no search bar.

**Comment by Dastan21** [comment]
• Is there any error related to FavoriteMedia in the console ?
• Test if it also happens with EmoteMenu from BD Settings

**Comment by Schleeem** [comment]
doesn't look like there's any favoritemedia errors that i can identify in the console. as for EmoteMenu, it just straight up doesn't appear when i turn it on.

**Comment by Dastan21** [comment]
Seems normal then. Last thing to check is the version of FavoriteMedia, even if you mentionned the update of 12/01/21 (of Discord or the plugin ?)

**Comment by Schleeem** [comment]
12/01/21 update of the plugin. it says the plugin is version 1.5.1, which i assume is the most recent since i reinstalled the plugin like half an hour ago.

**Comment by Dastan21** [comment]
It is indeed the last update, which should fix the bug... The plugin works fine on Discord Canary so your bug may be caused by another plugin, else I have no idea.

**Comment by Schleeem** [comment]
i'll try disabling other plugins and see if it fixes the issue.

**Comment by Dastan21** [comment]
Don't forget to restart Discord

**Comment by Schleeem** [comment]
it works now. not sure what the issue was but it's fixed now.
