### ISSUE TITLE
FavoriteMedia: Option to hide "Add to Favorites" button

### ISSUE THREAD

**Issue by QbDesu** [Dastan21/BDAddons#4]
I gotta be straight with you, I'll only really use the favorite image options of the plugin, even if it's still cool that it also supports other media types. The thing is, I can remove the Chat buttons and the Settings tabs but there is no option to hide the add to "Add to Favorites" button form videos or soundfiles. It would be nice if that was added as an option.

**Comment by Dastan21** [comment]
Added in abbc68b

**Comment by QbDesu** [comment]
You got a little mishap there when buttons position is set to left
https://github.com/Dastan21/BDAddons/commit/abbc68b4332ab586004c51766365f7c74ebef7d5#diff-aeab2b583f517c91a805ef7f3d93c1c921f667a511a26be490f0464a02895175R1660

Awesome work though. And thanks a lot for implementing all these changes so quickly!
