### ISSUE TITLE
[FavoriteMedia] Automatically download favorites

### ISSUE THREAD

**Issue by JonathanTippy** [Dastan21/BDAddons#40]
it would be nice if it had an option to automatically download favorite media.

**Comment by RidgePain** [comment]
i'd like this too, server i get most of my memes from gets termed a lot and makes my media crap itself. so autodownload/export and make an alternate link in the plugin to the downloaded media? maybe gif supports too?

**Comment by Dastan21** [comment]
You can download medias from a category regularly to keep them up to date on your computed (downloading many times medias from categories won't duplicates files, but make sure to rename them in an unique way otherwise they will get overwritten...)
