### ISSUE TITLE
[FavoriteMedia] Initial Media Context Menu Options

### ISSUE THREAD

**Issue by Aezaeo** [Dastan21/BDAddons#41]
It would make this plugin so much more effective if the user had the ability to either create a category from the context menu or to send media to an already made category via the context menu.

Instead of having to open up the FavoriteMedia window to add media to a category, one could do it right from the start via a context menu option brought up on the initial media being favorited. The same would go for creating a category, (ex. Right click an image -> Add to Favorites -> Create Category or add to an already made category.)

This would save time for the user having to favorite a piece of media then having to open the favoritemedia window and creating categories and sorting favorited media.

Also, side request if possible, the ability to have the FavortieMedia Window pop out to be it's own window instead of a sub window within the discord app. Kind of how we can pop out videos from people who are streaming within discord. This would allow for easier viewing of favorited media for users with a lot of favorited material for sorting purposes and reviewing. Currently the FavortieMedia sub-window is only able to be expanded horizontally.

Thanks for this awesome plugin, currently my most used.

**Comment by Dastan21** [comment]
Added more options for the context menu in v1.5.2.
I do not plan to do the sub window though.
Thanks for using this plugin!
