### ISSUE TITLE
[FavouriteMedia] Adding features to the GIF tab.

### ISSUE THREAD

**Issue by tort-oise** [Dastan21/BDAddons#42]
There's all these cool features in the image, video, and audio tab, yeah? Such as holding shift to send multiple, or to upload/download other types of media.
I honestly would love to have these as functions on the normal GIF tab, and not just on the tabs that your plugin provides. Why isn't it ported to those yet? Or, is it an issue on my end? I do have latest version, along with latest stable Discord.

**Comment by Dastan21** [comment]
It's because the GIF tab is a Discord feature that I did not recreated

**Comment by tort-oise** [comment]
Do you think you can implement these features? Would be great.

**Comment by Dastan21** [comment]
Implemented GIFs tab in 1.7.0
