### ISSUE TITLE
[FavouriteMedia] BUG: Feature Broke; Favoriting From Right Click Context Menu

### ISSUE THREAD

**Issue by Aezaeo** [Dastan21/BDAddons#45]
I don't know if it was an update to discord or a different plugin but the newest feature allowing us to move an image/video/audio to a created category from within the context menu has disappeared.

**Comment by Dastan21** [comment]
The ContextMenu is broken since the latest Discord. Everything added to the ContextMenus won't work until BetterDiscord will find a solution

**Comment by tort-oise** [comment]
Strange.. Works pretty fine for me. I'm able to add images and videos to the context menu.

**Comment by Dastan21** [comment]
Context menus are lazy loaded, this means we can't add items before context menu is rendered. But there is already a fix on ZLibrary. I'm waiting for the official release to fix my plugin's context menu.

**Comment by tort-oise** [comment]
Ah, I see. That's why. I run the latest commit of ZLib, instead of the release.

**Comment by Aezaeo** [comment]
yea, seems fixed now. must be that Zlib was updated.

**Comment by Aezaeo** [comment]
welp, nvm its not working again lol idk.

**Comment by Dastan21** [comment]
because ZLibrary update is not ready yet

**Comment by Dastan21** [comment]
Fixed in v1.5.5.
