### ISSUE TITLE
when sending image or vid it sends link

### ISSUE THREAD

**Issue by MOXYISCOOL** [Dastan21/BDAddons#47]
![image_2022-01-22_224123](https://user-images.githubusercontent.com/72164438/150657696-2da35dcf-7743-496a-8fa2-df2a06c00928.png)

soz bout the image i chose to use and normally it says media/discord stuff u know wat I mean but I have better links on so it says attachment is there a way to stop the link

**Comment by Dastan21** [comment]
I don't get what this has to do with my plugins. Except if you use **HideEmbedLink**, but I cannot reproduce it.

**Comment by Dastan21** [comment]
Ok I got an `<Attachment>`, I'm working on it.
