### ISSUE TITLE
FavoriteMedia: Chat buttons on the left instead

### ISSUE THREAD

**Issue by QbDesu** [Dastan21/BDAddons#5]
This one should be an easy fix/option:
The plugin is adding chat buttons on the of the emoji button, which is bad in my opinion because it automatically means it shifts around any buttons that are already there, meaning uses are forced to readjust and any muscle memory and stuff is gonna mess with them.
I'm gonna guess it was done that way because it means there is no gap in between the buttons that are used for expressions because of the gift button. But I would rather have them on the other side (and am hiding the gift button anyway).

The easy fix would be either having a config option to change this
https://github.com/Dastan21/BDAddons/blob/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js#L1611-L1613
to use `unshift` instead of push

**Comment by QbDesu** [comment]
While we are on the topic of chat buttons already, could you please add some sort of class or identifier to the chat buttons so themes can select for them?

**Comment by Dastan21** [comment]
Added a dropdown menu to choose 'left' (before everything) or 'right' (right after emoji button) abbc68b
