### ISSUE TITLE
The menu cuts off on the right and when using emojis the server icon of the emoji cuts off as well.

### ISSUE THREAD

**Issue by Anch0r1** [Dastan21/BDAddons#51]
This is very annoying. In the latest update it said it was fixed but the problem still persists for me

**Comment by Anch0r1** [comment]
![image](https://user-images.githubusercontent.com/83998791/150729228-7f437b2a-dd4a-48f8-b12c-9bfd540cf103.png)
this is what i mean. see the server icon at the right end?
this happens for images videos and gifs as well ( they cut off at the right end)

**Comment by Anch0r1** [comment]
if i resise the menu it changes the size of the emojis and they look bad

**Comment by Dastan21** [comment]
I can't reproduce

**Comment by Anch0r1** [comment]
![image](https://user-images.githubusercontent.com/83998791/151287193-4834b18c-1ae2-4172-bca7-2eb6061b0c88.png)
see this?
also the image video buttons arent appearing in the text bar

**Comment by Dastan21** [comment]
1. You Can stretch the box to left
2. Buttons should be fixed in 1.5.6 (updated yersteday)

**Comment by Anch0r1** [comment]
Stretching the box changes the size of emojis in the menu

**Comment by Dastan21** [comment]
Do you have themes ? Try to disable them and see if it works

**Comment by Anch0r1** [comment]
I do not have any themes

**Comment by Dastan21** [comment]
Any other plugin ?
Windows, Linux, MacOS ?

**Comment by Anch0r1** [comment]
The only other plugin I have is the ZeresPluginLibrary one 
Im running windows 11

**Comment by Dastan21** [comment]
Well I have no clue...

**Comment by Anch0r1** [comment]
._.

**Comment by Dastan21** [comment]
Does it happen with FavoriteMedia disabled ?

**Comment by Anch0r1** [comment]
nope

**Comment by Anch0r1** [comment]
This issue was fixed with the latest better discord update. (v1.5.0)
