### ISSUE TITLE
Can we have folders?

### ISSUE THREAD

**Issue by SINUSTECHTIPS** [Dastan21/BDAddons#52]
NVM IM DUMB THANK YOU FOR THE PLUGIN!

**Comment by SINUSTECHTIPS** [comment]
NVM, right click isn't working. idk how to make a folder without right clicking

**Comment by Dastan21** [comment]
Make sure FavoriteMedia is v1.5.5

**Comment by SINUSTECHTIPS** [comment]
just checked right now. it's 1.5.5
if im understanding the preview right, to create a new folder you just right click, correct? its not doing anything when i right click.

**Comment by Dastan21** [comment]
![menu](https://user-images.githubusercontent.com/58090137/151122446-92674553-e350-47b8-a06f-a16829f82cc4.png)

You have to right-click on the background to create categories.
There no right-click interaction for videos previews (if that's what you mentioned).

**Comment by SINUSTECHTIPS** [comment]
tried that: https://photos.app.goo.gl/nmUJKiLGVvKnhy5M7
still not working

**Comment by Dastan21** [comment]
Verify that you have the plugin `ZeresPluginLibrary` v2.0.0

**Comment by SINUSTECHTIPS** [comment]
Now it works, thank you! I think the plugin was outdated cause someone made a fix to it for nitroperks and it just never got updated. Either way thanks again for the help and the plugin broski this shi is great!~
