### ISSUE TITLE
[Favourite Media] Icons aren't showing

### ISSUE THREAD

**Issue by gamerinbg123** [Dastan21/BDAddons#53]
I tried restarting discord

**Comment by slmbebel** [comment]
I have the same problem

**Comment by barkinr** [comment]
me too!

**Comment by TxRichardxT** [comment]
I have the same problem too!

**Comment by Dastan21** [comment]
yep, they changed something in the textarea component

**Comment by TxRichardxT** [comment]
> yep, they changed something in the textarea component, i'm working on a fix

Thanks for the help take your time

**Comment by Dastan21** [comment]
Fixed in v1.5.6
