### ISSUE TITLE
[FavoriteMedia] Plug-in is not working

### ISSUE THREAD

**Issue by Zagreus12** [Dastan21/BDAddons#54]
I have to most recent update for the plug-in, however, there appears to be no button on the bottom right for any of the types of medias. I can't use the plug in because of it.

**Comment by Dastan21** [comment]
Works fine on Stable and Canary with FavoriteMedia v1.5.6. Maybe it is caused by another plugin.

**Comment by Zagreus12** [comment]
Thanks for the new update and the insanely quick response. <3
