### ISSUE TITLE
[FavoriteMedia] Cannot send as link when clicked on

### ISSUE THREAD

**Issue by gamerinbg123** [Dastan21/BDAddons#59]
When you hold shift it works

**Comment by gamerinbg123** [comment]
When you hold shift it works

**Comment by huangdangwibu** [comment]
same. error: 
`Uncaught TypeError: ComponentDispatch.dispatchToLastSubscribed is not a function
    at MediaCard.sendMedia (FavoriteMedia.plugin.js:876)`

**Comment by Dastan21** [comment]
Yup sry did a typo, fixed in v1.5.9.
