### ISSUE TITLE
Favorite media buttons appear after send message button

### ISSUE THREAD

**Issue by MrMansand** [Dastan21/BDAddons#64]
![image](https://user-images.githubusercontent.com/71806698/154876876-3a92bfd7-7d4c-45cd-bf60-6df9ab19800f.png)

**Comment by Dastan21** [comment]
SendButton has been deprecated and is no longer available on BetterDiscord website. The problem is from this plugin, you can give me the code so that I edit it for you.

**Comment by ikeman2003** [comment]
You can throw this into your custom CSS and it adjusts it.

/**Move send button and fix**/
.separator-3ng7S5 {
  order: 1;
  margin-right: 4px;
}

.buttonContainer-6W2Ep3 {
  margin-bottom: 3px;
}
