### ISSUE TITLE
[FavoriteMedia] Categories for favorited gifs

### ISSUE THREAD

**Issue by miles352** [Dastan21/BDAddons#7]
It would be nice if we could create categories in discords normal favorite gifs section.

**Comment by miles352** [comment]
Just thought of another idea, it would be cool to be able to hold shift to send multiple without the menu closing, like with emojis.

**Comment by Dastan21** [comment]
Added the 2nd suggestion in abbc68b.
Might look into the 1st one later.

**Comment by BeebzVivian** [comment]
@miles352 Unsure if you're aware already, but I've found that for Gifs I'm able to add them Categories in the Images:
> Right Click Context Menu > Favorite Media > Add > CATEGORY

From what I can tell this does not show the upper right star favorite icon filled in when hovering, but they should still animate and post correctly from Images from what I've seen.

**Comment by Zzeyy** [comment]
@Dastan21 when are you adding this then?

**Comment by Zzeyy** [comment]
You closed my request because of another 2 year old request.

**Comment by Dastan21** [comment]
Maybe, maybe not.

**Comment by Zzeyy** [comment]
Awesome!

**Comment by Dastan21** [comment]
Implemented GIFs tab in 1.7.0
