### ISSUE TITLE
Option to disable individual buttons in the typing field

### ISSUE THREAD

**Issue by Griffenskull** [Dastan21/BDAddons#70]
The ability to hide each individual icon in the bottom right hand corner in the typing field would allow for more customization and the ability to unclutter the screen. Perhaps an option to merge all 6 buttons that open up the different tabs of the same context menu into a single button would be useful as well

**Comment by Dastan21** [comment]
The options exist, or I misunderstood ?

**Comment by Griffenskull** [comment]
Did I just miss it? Which option do you think I'm talking about?

**Comment by Dastan21** [comment]
There are general settings and a category for each type of media in which you can hide the one button in the textarea, or the corresponding tab.

**Comment by Griffenskull** [comment]
ah, I figured it out. When I disabled the buttons for each it didn't actually work until a Discord restart

**Comment by Dastan21** [comment]
Glad it is working again :)
