### ISSUE TITLE
The image, video and audio buttons doesnt appear

### ISSUE THREAD

**Issue by TxRichardxT** [Dastan21/BDAddons#73]
![Captura de pantalla 2022-04-08 213428](https://user-images.githubusercontent.com/94150125/162553411-db12964f-ebd1-4775-8a0d-bea110f42dd1.png)

The buttons to open the media doesnt show i dont know if its me or its a bug i tried restarting discord and still doesnt work

**Comment by ScottsplaysSus** [comment]
Same here, hope the devs can fix it ASAP :)

**Comment by Dastan21** [comment]
Fixed in 1.5.15

**Comment by ScottsplaysSus** [comment]
Thanks for fixing, it worked now :D
