### ISSUE TITLE
Videos doesnt reply with right click upload option

### ISSUE THREAD

**Issue by TxRichardxT** [Dastan21/BDAddons#76]
idk if its a bug or its disabled but before i could reply to someone with a video just pressing right click - upload - normal but now when i hit the the reply button and try to do the same proces the video sends like normal no replying to the person i wanted to, is there any way to fix this or its not possible again
![Captura de pantalla 2022-04-12 231714](https://user-images.githubusercontent.com/94150125/163102105-834b596b-aa31-4225-9c95-491323b5fbd1.png)

**Comment by karimawii** [comment]
Audios too with normal click and upload (which are basically the same thing)

**Comment by Dastan21** [comment]
Fixed in v1.15.17
