### ISSUE TITLE
[FavouriteMedia] Ability to Add Text with Uploads

### ISSUE THREAD

**Issue by BeebzVivian** [Dastan21/BDAddons#78]
Love the Plugin! Already having a good time feeling nostalgic about when I used to use reaction images/gifs a lot more than I do now. 

I'd like to suggest being able to have uploaded media attach to what text is already in the box before being sent or simply be uploaded as an attachment without automatically being sent so the User can add text afterward, whichever is easier!

I've noticed that the traditional left-click attaches the media as a link. These make sense to immediately upload since Discord hides links to images in single posts if theres no accompanying text. What I've also noticed however, is that the links do remain attached to any text already put in the image box. Right-clicking and uploading media however, (Holding Shift or Otherwise) Will always attach or upload on its own regardless of text in the box.

I would be great to be able to do this so as to not lose context of text and reactions for faster chats, finding images more easily when searching a channel in the future (since the image will be attached directly to the context), as well as prevent the dreaded "double icon" look on mobile.

I've attached a video describing what I mean quickly. Thank you for your time!

https://user-images.githubusercontent.com/7242397/167003350-128ad44e-9e62-4f22-8b43-f32af5465ca6.mov

Edited: Video Reupload

**Comment by Dastan21** [comment]
Hey, thank for your suggestion, I might add this feature in the next update. Btw the video doesn't seem to be working...

**Comment by BeebzVivian** [comment]
That would be awesome! Looking forward to it. I wasnt sure if it only wasnt working on my end because it seemed strange for an mp4 to not work. Reuploaded it as mov and its fine on my end but hopefully that will clear anything up! Much appreciated.

**Comment by Dastan21** [comment]
Done in v1.5.18 :)

**Comment by BeebzVivian** [comment]
I am loving this! Thank you so much 👍 
Very low priority but something I wanted to bring up something that I noticed by accident, could be intentional, but unsure: Any `@user` mentions in the text box get discarded when uploading the image, whether by itself, or at the start or end of a regular string of text. Any text that isnt the Mention still goes through though! Messages using the Discord Reply function also work properly too! Though I'm not sure if that was the case or not before this update. Thanks again! Just wanted to let you know :)
