### ISSUE TITLE
FavoriteMedia TypeError: Cannot read property 'width' of undefined

### ISSUE THREAD

**Issue by VanQWisher** [Dastan21/BDAddons#79]
Object.callback (FavoriteMedia.plugin.js:1849)

I can replicate this by opening the model window for images, video, or audio and switching text channels/servers

Quick fix:
`width: propsImg.style?.width,
height: propsImg.style?.height`

**Comment by Dastan21** [comment]
What shortcut do you use ?

**Comment by bob-carter** [comment]
Where do I add that code?

**Comment by Dastan21** [comment]
How do you reproduce this ?

**Comment by bob-carter** [comment]
Honestly, how comes this bug keeps returning?

**Comment by Dastan21** [comment]
Do you have this error ?

**Comment by bob-carter** [comment]
Where the image isn't displayed right and it makes it imposible click anything because it's all messed up. I mean last time I was told it was because of width not being recognized

**Comment by Dastan21** [comment]
https://github.com/Dastan21/BDAddons/issues/109#issuecomment-1219146067 maybe this is what you're looking for.

**Comment by bob-carter** [comment]
Maybe, but I'm fairly sure this is the same thing, as always I just delete everything and reinstall, since manually resetting everything is insanely tedious, the fact this issue keeps repapering in newer builds is annoying me to no end.

**Comment by Dastan21** [comment]
Thé latest version is 1.5.27, you can download it manually here: https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js
