### ISSUE TITLE
FavouriteMedia buttons still appear when in a channel without speaking perms.

### ISSUE THREAD

**Issue by OsoaGitHub** [Dastan21/BDAddons#8]
![In a channel with speaking perms](https://user-images.githubusercontent.com/33041004/125202024-ab668c00-e269-11eb-8ff2-def8be003eeb.png)

![In a channel without speaking perms](https://user-images.githubusercontent.com/33041004/125202031-bae5d500-e269-11eb-9d53-e06b25d20421.png)

**Comment by Dastan21** [comment]
Fixed in 10a3afb
