### ISSUE TITLE
[FavoriteMedia] Sometimes the Add to Favorites button appears to the right instead of top right

### ISSUE THREAD

**Issue by Visne** [Dastan21/BDAddons#80]
For example:

![image](https://user-images.githubusercontent.com/39844191/167854254-6ae4385e-10cc-4e47-a3ab-fd49a76c87b0.png)

**Comment by Dastan21** [comment]
The icon appears at the middle right because it is a video ans videos have the download icon already positioned at top-right.

**Comment by Visne** [comment]
That makes sense, is it possible to make an option to move the icon? I find the right side positioning somewhat awkward. Ideally, it would be placed next to the download button but I'm not sure if this is possible.

**Comment by Visne** [comment]
Also, videos that are embedded URLs do not have a download button anyways, so they can just have the star at the top right.

**Comment by Dastan21** [comment]
Fixed in 1.5.28
