### ISSUE TITLE
Doesn't work with Ubereats

### ISSUE THREAD

**Issue by aRcane305** [Dastan21/BDAddons#81]
![image](https://user-images.githubusercontent.com/69064453/168195725-b9f834d8-afca-4c14-91b3-092afe4132c5.png)
![image](https://user-images.githubusercontent.com/69064453/168195751-fb7d662b-31eb-41d0-ad3c-5e903010c64a.png)

Doesn't work with this particular type of Ubereats link: https://www.ubereats.com/au/orders, https://www.ubereats.com/au/feed works fine with the embedder. 

The issue is there is no link embedded.

**Comment by Dastan21** [comment]
With which plugin ?

**Comment by aRcane305** [comment]
https://github.com/Dastan21/BDAddons/tree/main/plugins/HideEmbedLink
