### ISSUE TITLE
controls and preview not working after update!

### ISSUE THREAD

**Issue by amoruwu** [Dastan21/BDAddons#85]
https://gyazo.com/b100d0c74212300d2e0efeb2969970b1
for some reason a lot of things broke after the update,
including images.

**Comment by Dastan21** [comment]
I'm on it, just figuring another bug #84. If you experience smth similar tell me there :)

**Comment by Dastan21** [comment]
Fixed in v1.6.1.

**Comment by amoruwu** [comment]
no issues similar to the other guy, I seen to be experiencing a different set of issues, thank you for adding the label bug, I forgot to do that. 
https://gyazo.com/6039c9d6df38fb9a947da7e0aec9d342 all my old images seem to not load, the only one that loads I just saved right now.

**Comment by amoruwu** [comment]
alright thank you.
