### ISSUE TITLE
FavoriteMedia: Can't scroll Category list in right click.

### ISSUE THREAD

**Issue by bgiesing** [Dastan21/BDAddons#86]
I have 20+ categories and I can't see them all cause the right click "Add" menu doesn't scroll.

**Comment by Dastan21** [comment]
This, right ?

![Discord_aY2vUa4RSw](https://user-images.githubusercontent.com/58090137/170856793-3802bd5a-f909-45d7-9aef-a764c7bdfee4.gif)

**Comment by Dastan21** [comment]
Try disabling your themes

**Comment by bgiesing** [comment]
Not using any

**Comment by Dastan21** [comment]
Not working since one of the latest updates ?

**Comment by bgiesing** [comment]
IDK, I never used categories before today since I installed the latest update for the plugin. Didn't even know they existed before now

**Comment by bgiesing** [comment]
Tried adding more categories to test and somehow now I have 2 categories with different names and colors but mirroring the same gifs, removing one category removes both

**Comment by Dastan21** [comment]
Normally you could not create many categories with the same name

**Comment by bgiesing** [comment]
They are all completely different names

**Comment by Dastan21** [comment]
![image](https://user-images.githubusercontent.com/58090137/170858716-5ea4aee9-0253-40f0-8abd-72a86c4a8bf2.png)

**Comment by Dastan21** [comment]
Idk, plus the scroll things, so weird...
