### ISSUE TITLE
[FavortieMedia] BUG: New Custom GIFs Tab

### ISSUE THREAD

**Issue by Aezaeo** [Dastan21/BDAddons#87]
There are a few issues with the new Custom GIFs tab. I'll try my best to explain.

First issue: 

I have created multiple categories to place GIFs in but after adding a GIF to a category, that same GIF gets placed in every other category I created as well. For example:

I create categories "A", "B", and "C. I add a GIF to category "A". That GIF then also gets placed in categories "A", "B",  and "C".

Second issue: 

When opening up the new GIF tab to view the GIFs you've favorited, GIFs with sound start playing. So, if I have 3 GIFs with sound favorited, all 3 GIFs will play audio simultaneously. Is it possible to have all GIFs with sound defaulted to being muted?

Third issue: 

I had a different idea of what you meant when you said you were going to add a custom GIFs tab. I thought it was going to be separate from the default GIFs tab and not replacing it entirely. With the way it is currently, any GIFs I have favorited to the default Discord GIF tab are no longer visible, along with the default trending categories. The current fix is to disable the "Custom GIFs Tab" to get default view. It's basically acting the same as the setting option "Show only favorites in GIFs tab".

The main issue with the default Favorited GIFs tab is that it has a hard cap of how many GIFs one can favorite. Your plugin is perfect because there is no cap for favorited GIFs. In my particular use case, I haven't migrated all the GIFs I've favorited over to FavoriteMedia. So I tend to go through the default GIF tab on occasion. Currently with the way you have the Custom GIFs tab set, I'd have to disable/reenable to make it work the way I needed it to.

The way you had it before the more recent updates allowed me to just create categories within the "Images" tab and I was able to add GIFs to the categories I created. There was also the non-issue of the audio for a GIF with sound, playing when viewing the category.

I personally think it would be much more user friendly to just have the new custom GIFs tab separated just like the "Images", "Video", and "Audio" tabs. That way a user who has Favorited GIFs via the default discord way can still view those, as well as, have access to use the trending categories.

As I've said before, this is my most used plugin so I appreciate any and all time you put into it, thanks.

**Comment by Dastan21** [comment]
Revert to 1.5.19, will try smth different.

**Comment by Aezaeo** [comment]
Understood.

**Comment by Dastan21** [comment]
How do you know this is the limit of fav GIFs ? I have favorited hundreds and still can.
