### ISSUE TITLE
[FavoriteMedia] Remove favourite image/video/audio if source link is no longer available

### ISSUE THREAD

**Issue by amoruwu** [Dastan21/BDAddons#91]
source link removed for lots of images and videos I got, now I have to remove each one individually...
love this plugin tho! [image](https://i.gyazo.com/269cb9380f0748cc60460ee23f0e1134.png)

**Comment by Dastan21** [comment]
Added in 1.7.1, 1.7.2 or 1.7.3 idk but there is now a setting in the latest version
