### ISSUE TITLE
Media tends to fail loading after some times has passed

### ISSUE THREAD

**Issue by LockeyCentral** [Dastan21/BDAddons#92]
It may be due to having lots of media saved, but after a certain amount of time has passed or if attempting to add more media, one of two things may happen:

1) The media fails to load
<img width="204" alt="Screen Shot 2022-06-27 at 9 46 32 PM" src="https://user-images.githubusercontent.com/68749417/176069328-a3489bfa-e44d-4a51-be81-e9e0d1b2af20.png">

**or**

2) The media does load, but will not appear when you try to post it
<img width="282" alt="Screen Shot 2022-06-27 at 9 47 24 PM" src="https://user-images.githubusercontent.com/68749417/176069636-166dc3b3-471d-4029-b024-37f25133ff4e.png">

Clicking the attachment hyperlink will send you to this page
<img width="1789" alt="Screen Shot 2022-06-27 at 9 51 04 PM" src="https://user-images.githubusercontent.com/68749417/176070105-dca1daf9-f6ae-44a7-923c-e86221f91251.png">

**Comment by Dastan21** [comment]
It happens because the source message has been deleted. Cannot really do anything 😢
