### ISSUE TITLE
[FavoriteMedia] Replace GIF tab searching 

### ISSUE THREAD

**Issue by Reibies** [Dastan21/BDAddons#93]
I wonder if it's possible down the road, to either still allow for the default type of searching via the replaced GIF tab, or if there can be an option to have both the original GIF tab alongside Favorite Media's version.

**Comment by Dastan21** [comment]
I tried already but got many problems. Maybe when I'll get the motivation again.

**Comment by Dastan21** [comment]
Reworked the GIFs tab in 1.7.0
