### ISSUE TITLE
[FavoriteMedia] Compilation error

### ISSUE THREAD

**Issue by maenDisease** [Dastan21/BDAddons#94]
Plugin is unable to load.
Extra context: Discord has made changes around the role area in the user pop-out.

Canary 135765 (6fd3378)
BetterDiscord 1.5.3
Host 1.0.47 Windows 10 64-Bit (10.0.19044)

![image](https://user-images.githubusercontent.com/90428263/178065143-45afe860-f3bd-4dc2-974a-a40cf2825b51.png)

**Comment by Dastan21** [comment]
Thx for the report, imma make a quick fix.

**Comment by Dastan21** [comment]
Fixed in 1.5.20
