### ISSUE TITLE
FavoriteMedia - "Could not be constructed" error

### ISSUE THREAD

**Issue by Pokesketch** [Dastan21/BDAddons#95]
![Capture](https://user-images.githubusercontent.com/62312740/178336527-0390292b-0ca3-4cbb-a48a-f7c2a13d97bc.PNG)
Opened up Discord to be met with this on startup.

**Comment by gage64** [comment]
i'm getting the same error as well 
![image](https://user-images.githubusercontent.com/28501503/178342094-67810529-adb1-436c-9fd3-6e51727d5b0d.png)

**Comment by amoruwu** [comment]
![image](https://user-images.githubusercontent.com/78520579/178362452-3c06b61a-1941-4c0d-885a-df94373066d5.png)
same here

**Comment by Dastan21** [comment]
Cannot do anything until the error reaches me.

**Comment by JustaFloatingEyeYT** [comment]
Today I got the same issue, I even tried reinstalling the plugin and the same thing happened. Is it an issue with the config?

**Comment by pipe3241** [comment]
I just got the same issue.

**Comment by JustaFloatingEyeYT** [comment]
> Is it an issue with the config?

I tried removing the config, that did not fix the issue.

**Comment by JustaFloatingEyeYT** [comment]
> Quick fix, line 92:
> 
> old: `role: WebpackModules.getByProps("roleIcon", "roleName", "roleCircle"),` new `role: WebpackModules.getByProps("roleCircle"),`

This fixes it, nice.

**Comment by Dastan21** [comment]
I think most of the problems are caused by the previous version crash. In consequence, the auto-updater cannot do its job since the plugin cannot be started.
To fix that, download manually the latest version of the plugin [here](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js).

**Comment by master3395** [comment]
> I think most of the problems are caused by the previous version crash. In consequence, the auto-updater cannot do its job since the plugin cannot be started. To fix that, download manually the latest version of the plugin [here](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js).

You are correct, that 1.20 instead of 1.18 worked :D

**Comment by sapow345** [comment]
so what am i supposed to do to fix it?? im confused in this whole conversation

**Comment by master3395** [comment]
> so what am i supposed to do to fix it?? im confused in this whole conversation ![image](https://user-images.githubusercontent.com/109186894/178620160-400f1b72-9a44-43ef-9b3b-f5892729c3af.png)

Download the latest file and overwrite the existing file in your plugins folder from [here.](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js)

**Comment by Zabivodka** [comment]
> Download what? It's literally a wall of text with no option to download anything lol.

**Comment by Dastan21** [comment]
Click on the blue word "here" from the previous comment.

**Comment by MahdeenSky** [comment]
[Download](https://filebin.net/p6voudq3vqfbhug7) this. Then, replace the file in Plugins [Folder](https://i.imgur.com/RMZTGgV.png).

**Comment by soulshot96** [comment]
> I think most of the problems are caused by the previous version crash. In consequence, the auto-updater cannot do its job since the plugin cannot be started. To fix that, download manually the latest version of the plugin [here](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js).

Cheers for the fix. Worked like a charm.

**Comment by GITwithWillow** [comment]
> [Download](https://filebin.net/p6voudq3vqfbhug7) this. Then, replace the file in Plugins [Folder](https://i.imgur.com/RMZTGgV.png).

links dead, anyone else have a alternative source?

**Comment by Dastan21** [comment]
> I think most of the problems are caused by the previous version crash. In consequence, the auto-updater cannot do its job since the plugin cannot be started. To fix that, download manually the latest version of the plugin [here](https://github.com/Dastan21/BDAddons/raw/main/plugins/FavoriteMedia/FavoriteMedia.plugin.js).
