### ISSUE TITLE
FavoriteMedia - Gifs going in images section instead of Gifs section

### ISSUE THREAD

**Issue by Overimagine1** [Dastan21/BDAddons#96]
FavoriteMedia has started putting my gifs in the images section. They are supposed to go in the gif section.

![image](https://user-images.githubusercontent.com/79660414/178346785-d5eed2a0-251c-4527-b74e-4e082865bdcc.png)

The star for images seems to be overlapping the star that's intended for gifs. I discovered this as I making this issue.

**Comment by SynthwaveFox** [comment]
Experiencing this as well, GIFs get put in the images section, making it impossible to favorite GIFs.

**Comment by bob-carter** [comment]
Honestly, I like this, and would suggest making this a feature if it gets removed. Could also remove gif button as well.

**Comment by Dastan21** [comment]
I got the bug once and cannot reproduce it on Stable and Canary.

**Comment by Reibies** [comment]
Happens with non-tenor images for me. If I link something from places like tumblr it goes to images. 
I might backup my config and clear to see if it's just an error with that.

**Comment by Dastan21** [comment]
Fixed in v1.5.22
