### ISSUE TITLE
[FavoriteMedia] "Well This Is Awkard" Crash on FavoriteMedia button click

### ISSUE THREAD

**Issue by maenDisease** [Dastan21/BDAddons#98]
Pressing a FavoriteMedia button containing a saved media will crash Discord with "Well This Is Awkward".
Canary 136051 (4222d5b)
BetterDiscord 1.5.3
Host 1.0.47 Windows 10 64-Bit (10.0.19044)

![image](https://user-images.githubusercontent.com/90428263/178362867-32e38be4-4b67-4b23-b688-65949f3143b3.png)

If there's no crashing then this error is made when clicking any of the popout/textarea favoritemedia buttons and prevents favoriting
![image](https://user-images.githubusercontent.com/90428263/178364670-ab2e1777-4105-4cf6-931c-be04ee024309.png)

**Comment by master3395** [comment]
It's related to this when you start discord.

Stable 136240 (9a882e6)
BetterDiscord 1.5.3
Host 1.0.9005 Windows 10 64-Bit (10.0.22000)

![image](https://user-images.githubusercontent.com/4199669/178582102-a1486a24-a00f-4dc2-9a23-6568266d9771.png)

**Comment by maenDisease** [comment]
> It's related to this when you start discord.
> 
> Stable 136240 (9a882e6) BetterDiscord 1.5.3 Host 1.0.9005 Windows 10 64-Bit (10.0.22000)
> 
> ![image](https://user-images.githubusercontent.com/4199669/178582102-a1486a24-a00f-4dc2-9a23-6568266d9771.png)
> 
> #95

The issue you refer to is due to a change in the role module, which was addressed in 1.5.20z
